/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AgendaCtrl;
import controller.ConsultaCtrl;
import controller.GenericCtrl;
import controller.MedicoCtrl;
import controller.PacienteCtrl;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Agenda;
import model.Consulta;
import model.Generic;
import model.Medico;
import model.Paciente;

/**
 *
 * @author leogo
 */
public class AgendaConsView extends javax.swing.JInternalFrame {

    Consulta consulta = new Consulta();
    ConsultaCtrl consultaCtrl = new ConsultaCtrl();

    Paciente paciente = new Paciente();
    PacienteCtrl pacienteCtrl = new PacienteCtrl();
    ArrayList<Paciente> listarPaciente = new ArrayList<>();

    Medico medico = new Medico();
    MedicoCtrl medicoCtrl = new MedicoCtrl();
    ArrayList<Medico> listarMedico = new ArrayList<>();

    Agenda agenda = new Agenda();
    AgendaCtrl agendaCtrl = new AgendaCtrl();
    ArrayList<Generic> listaAgendaMedPac = new ArrayList<>();
    ArrayList<Generic> listaConsultaMedPac = new ArrayList<>();
    GenericCtrl genericCtrl = new GenericCtrl();

    String salvarAlterar;

    /**
     * Creates new form AgendaConsView
     */
    public AgendaConsView() {
        initComponents();
        pegarDataHoraSistema();
        carregarAgenda();
        carregarConsulta();
        habilitarDesabilitar(false);
        habilitarDesabilitar2(false);

        carregarMedico();
        carregarPaciente();

        retornarMedico();
        retornarPaciente();

        carregarMedicos();
        carregarPacientes();

        retornarMedicos();
        retornarPacientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogConsulta = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcb_paciente1 = new componentes.UJComboBox();
        jcb_medico1 = new componentes.UJComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_frequencia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lbl_paciente1 = new javax.swing.JLabel();
        lbl_medico1 = new javax.swing.JLabel();
        jcb_realiza = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lbl_cosulta = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txt_diastolica = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_sistolica = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jcb_dateTime = new javax.swing.JFormattedTextField();
        btn_salvar1 = new javax.swing.JButton();
        btn_editar1 = new javax.swing.JButton();
        btn_novo1 = new javax.swing.JButton();
        btn_fechar1 = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_consulta = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_salvar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_agenda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jcb_medico = new componentes.UJComboBox();
        jcb_paciente = new componentes.UJComboBox();
        lbl_medico = new javax.swing.JLabel();
        lbl_paciente = new javax.swing.JLabel();
        jDateChooserData = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_hora = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_motivo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcb_realizada = new javax.swing.JComboBox<>();
        lbl_agenda = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btn_editar = new javax.swing.JButton();
        btn_realizarCons = new javax.swing.JButton();

        jDialogConsulta.setTitle("Realizar Consulta");
        jDialogConsulta.setBackground(new java.awt.Color(255, 255, 255));
        jDialogConsulta.setBounds(new java.awt.Rectangle(300, 100, 736, 468));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("");
        jPanel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Paciente");

        jcb_paciente1.setEditable(true);
        jcb_paciente1.setAutocompletar(true);
        jcb_paciente1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_paciente1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcb_paciente1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jcb_medico1.setEditable(true);
        jcb_medico1.setAutocompletar(true);
        jcb_medico1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_medico1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcb_medico1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Médico");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Frequência BPM");

        txt_frequencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Data da Consulta");

        lbl_paciente1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_paciente1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_paciente1.setText("IdPaciente");

        lbl_medico1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_medico1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_medico1.setText("IdMedico");

        jcb_realiza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_realiza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SIM", "NÃO" }));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Consulta Realizada?");

        jLabel15.setText("Consultas Realizadas");

        jPanel12.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        lbl_cosulta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_cosulta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cosulta.setText("idConsulta");

        jLabel16.setText("Consultas não Realizadas");

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        txt_diastolica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));
        txt_diastolica.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Diastólica");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Sistólica");

        try {
            txt_sistolica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_sistolica.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pressão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        try {
            jcb_dateTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jcb_dateTime.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jcb_dateTime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_dateTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcb_dateTimeFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jcb_paciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_medico1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_paciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_cosulta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(lbl_medico1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jcb_realiza, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_sistolica, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txt_diastolica, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel17))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_frequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jcb_dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel15)))))
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_paciente1)
                    .addComponent(lbl_cosulta)
                    .addComponent(lbl_medico1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_paciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_medico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_realiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_sistolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_diastolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_frequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcb_dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(13, 13, 13))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)))
        );

        btn_salvar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_salvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_24px.png"))); // NOI18N
        btn_salvar1.setText("Salvar");
        btn_salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar1ActionPerformed(evt);
            }
        });

        btn_editar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_editar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit_24px.png"))); // NOI18N
        btn_editar1.setText("Editar");
        btn_editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar1ActionPerformed(evt);
            }
        });

        btn_novo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Create_24px.png"))); // NOI18N
        btn_novo1.setText("Novo");
        btn_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo1ActionPerformed(evt);
            }
        });

        btn_fechar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_fechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_fechar1.setText("Fechar");
        btn_fechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechar1ActionPerformed(evt);
            }
        });

        btn_apagar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash Can_24px.png"))); // NOI18N
        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        jt_consulta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jt_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Paciente", "Médico", "Sistólica", "Diastólica", "Frequência BPM", "Data da Consulta", "Consulta Finalizada?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_consulta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(jt_consulta);
        if (jt_consulta.getColumnModel().getColumnCount() > 0) {
            jt_consulta.getColumnModel().getColumn(1).setMinWidth(150);
            jt_consulta.getColumnModel().getColumn(1).setPreferredWidth(200);
            jt_consulta.getColumnModel().getColumn(2).setMinWidth(150);
            jt_consulta.getColumnModel().getColumn(2).setPreferredWidth(200);
            jt_consulta.getColumnModel().getColumn(3).setMinWidth(80);
            jt_consulta.getColumnModel().getColumn(3).setPreferredWidth(90);
            jt_consulta.getColumnModel().getColumn(4).setMinWidth(80);
            jt_consulta.getColumnModel().getColumn(4).setPreferredWidth(90);
            jt_consulta.getColumnModel().getColumn(5).setMinWidth(80);
            jt_consulta.getColumnModel().getColumn(5).setPreferredWidth(90);
            jt_consulta.getColumnModel().getColumn(6).setMinWidth(120);
            jt_consulta.getColumnModel().getColumn(6).setPreferredWidth(150);
            jt_consulta.getColumnModel().getColumn(7).setMinWidth(120);
            jt_consulta.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_fechar1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_apagar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_novo1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar1))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar1)
                    .addComponent(btn_editar1)
                    .addComponent(btn_novo1)
                    .addComponent(btn_fechar1)
                    .addComponent(btn_apagar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogConsultaLayout = new javax.swing.GroupLayout(jDialogConsulta.getContentPane());
        jDialogConsulta.getContentPane().setLayout(jDialogConsultaLayout);
        jDialogConsultaLayout.setHorizontalGroup(
            jDialogConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogConsultaLayout.setVerticalGroup(
            jDialogConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Agendar Consulta");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_24px.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Create_24px.png"))); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        jt_agenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jt_agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Paciente", "Médico", "Data", "Horário", "Descrição", "Consulta Realizada?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_agenda.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jt_agenda);
        if (jt_agenda.getColumnModel().getColumnCount() > 0) {
            jt_agenda.getColumnModel().getColumn(1).setMinWidth(150);
            jt_agenda.getColumnModel().getColumn(1).setPreferredWidth(200);
            jt_agenda.getColumnModel().getColumn(2).setMinWidth(150);
            jt_agenda.getColumnModel().getColumn(2).setPreferredWidth(200);
            jt_agenda.getColumnModel().getColumn(3).setMinWidth(100);
            jt_agenda.getColumnModel().getColumn(3).setPreferredWidth(120);
            jt_agenda.getColumnModel().getColumn(4).setMinWidth(80);
            jt_agenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            jt_agenda.getColumnModel().getColumn(5).setMinWidth(200);
            jt_agenda.getColumnModel().getColumn(5).setPreferredWidth(250);
            jt_agenda.getColumnModel().getColumn(6).setMinWidth(110);
            jt_agenda.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agendamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Descrição da Consulta");

        jcb_medico.setEditable(true);
        jcb_medico.setAutocompletar(true);
        jcb_medico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_medico.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcb_medicoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jcb_paciente.setEditable(true);
        jcb_paciente.setAutocompletar(true);
        jcb_paciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_paciente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcb_pacientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        lbl_medico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_medico.setForeground(new java.awt.Color(255, 255, 255));
        lbl_medico.setText("IdMedico");

        lbl_paciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_paciente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_paciente.setText("IdPaciente");

        jDateChooserData.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Data da Consulta");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Paciente");

        try {
            txt_hora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_hora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Horário da Consulta");

        txt_motivo.setColumns(20);
        txt_motivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_motivo.setRows(5);
        jScrollPane1.setViewportView(txt_motivo);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Médico");

        jLabel3.setText("Consulta Realizada?");

        jcb_realizada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SIM", "NÃO" }));

        lbl_agenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_agenda.setForeground(new java.awt.Color(255, 255, 255));
        lbl_agenda.setText("IdAgenda");

        jLabel9.setText("Consultas não Realizadas");

        jLabel10.setText("Consultas com Data Vencida");

        jLabel8.setText("Consultas Realizadas");

        jPanel9.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(314, 314, 314))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcb_medico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooserData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 50, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jcb_realizada, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(lbl_medico)
                .addGap(18, 18, 18)
                .addComponent(lbl_paciente)
                .addGap(18, 18, 18)
                .addComponent(lbl_agenda)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_medico)
                    .addComponent(lbl_paciente)
                    .addComponent(lbl_agenda))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jcb_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcb_realizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btn_editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit_24px.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_realizarCons.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_realizarCons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Therapy_24px.png"))); // NOI18N
        btn_realizarCons.setText("Realizar Consulta");
        btn_realizarCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_realizarConsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_fechar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_realizarCons)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_novo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_novo)
                    .addComponent(btn_fechar)
                    .addComponent(btn_editar)
                    .addComponent(btn_realizarCons))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(350, 60, 662, 585);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        if (salvarAlterar.equals("salvar")) {
            salvarAgenda();
            limparTable();
            carregarAgenda();
        } else if (salvarAlterar.equals("alterar")) {
            alterarAgenda();
            limparTable();
            carregarAgenda();
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        salvarAlterar = "salvar";
        carregarMedicos();
        carregarPacientes();
        retornarPaciente();
        retornarMedico();
        habilitarDesabilitar(true);
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        salvarAlterar = "alterar";
        if (jt_agenda.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "AVISO", JOptionPane.ERROR_MESSAGE);
        } else {
            selectAgendaCons();
            habilitarDesabilitar(true);
            jcb_realizada.setEnabled(true);
            if (lbl_medico.getText().equals("0") || lbl_paciente.getText().equals("0")) {
                jcb_medico.setSelectedItem("SELECIONE O MÉDICO");
                jcb_paciente.setSelectedItem("SELECIONE O PACIENTE");
            } else {
                medico = medicoCtrl.retoMedicoIdCtrl(Integer.parseInt(lbl_medico.getText()));
                jcb_medico.setSelectedItem(medico.getNome().toUpperCase());
                paciente = pacienteCtrl.retoPacienteIdCtrl(Integer.parseInt(lbl_paciente.getText()));
                jcb_paciente.setSelectedItem(paciente.getNome().toUpperCase());
            }
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void jcb_pacientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcb_pacientePopupMenuWillBecomeInvisible
        if (jcb_paciente.isPopupVisible()) {
            preencherCod();
        }
    }//GEN-LAST:event_jcb_pacientePopupMenuWillBecomeInvisible

    private void jcb_medicoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcb_medicoPopupMenuWillBecomeInvisible
        if (jcb_medico.isPopupVisible()) {
            preencherCod();
        }
    }//GEN-LAST:event_jcb_medicoPopupMenuWillBecomeInvisible

    private void jcb_paciente1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcb_paciente1PopupMenuWillBecomeInvisible
        if (jcb_paciente1.isPopupVisible()) {
            preencherCod2();
        }
    }//GEN-LAST:event_jcb_paciente1PopupMenuWillBecomeInvisible

    private void jcb_medico1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcb_medico1PopupMenuWillBecomeInvisible
        if (jcb_medico1.isPopupVisible()) {
            preencherCod2();
        }
    }//GEN-LAST:event_jcb_medico1PopupMenuWillBecomeInvisible

    private void jcb_dateTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_dateTimeFocusGained
        jcb_dateTime.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date(System.currentTimeMillis())));
    }//GEN-LAST:event_jcb_dateTimeFocusGained

    private void btn_salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar1ActionPerformed
        if (salvarAlterar.equals("salvar")) {
            salvar();
        } else if (salvarAlterar.equals("alterar")) {
            alterarConsulta();
        }
    }//GEN-LAST:event_btn_salvar1ActionPerformed

    private void btn_editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar1ActionPerformed
        salvarAlterar = "alterar";
        if (jt_consulta.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "AVISO", JOptionPane.ERROR_MESSAGE);
        } else {
            selectConsulta();
            habilitarDesabilitar2(true);
            if (lbl_medico1.getText().equals("0") || lbl_paciente1.getText().equals("0")) {
                jcb_paciente1.setSelectedItem("SELEIONE O PACIENTE");
                jcb_medico1.setSelectedItem("SELEIONE O MÉDICO");
            } else {
                medico = medicoCtrl.retoMedicoIdCtrl(Integer.parseInt(lbl_medico1.getText()));
                jcb_medico1.setSelectedItem(medico.getNome().toUpperCase());
                paciente = pacienteCtrl.retoPacienteIdCtrl(Integer.parseInt(lbl_paciente1.getText()));
                jcb_paciente1.setSelectedItem(paciente.getNome().toUpperCase());
            }
        }
    }//GEN-LAST:event_btn_editar1ActionPerformed

    private void btn_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo1ActionPerformed
        salvarAlterar = "salvar";
        habilitarDesabilitar2(true);
    }//GEN-LAST:event_btn_novo1ActionPerformed

    private void btn_fechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechar1ActionPerformed
        jDialogConsulta.dispose();
    }//GEN-LAST:event_btn_fechar1ActionPerformed

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        int d = JOptionPane.showConfirmDialog(null, "Deseja apagar este registro?", "AVISO", JOptionPane.YES_NO_OPTION);
        if (d == 0) {
            try {
                if (jt_consulta.getSelectedRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Selecione um registro", "AVISO", JOptionPane.ERROR_MESSAGE);
                } else {
                    int[] rows = jt_consulta.getSelectedRows();
                    for (int i = 0; i < rows.length; i++) {
                        int codigo = (int) jt_consulta.getValueAt(rows[i], 0);
                        consultaCtrl.deletConsultaCtrl(codigo);
                    }
                    JOptionPane.showMessageDialog(null, "Resgistro apagado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao tentar apagar registro!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        limparTabela2();
        carregarConsulta();
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void btn_realizarConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_realizarConsActionPerformed
        salvarAlterar = "salvar";
        habilitarDesabilitar2(true);
        if (jt_agenda.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "AVISO", JOptionPane.ERROR_MESSAGE);
        } else {
            retornarAgendaCons();
            jDialogConsulta.setModal(true);
            jDialogConsulta.setVisible(true);
            if (lbl_medico1.getText().equals("0") || lbl_paciente1.getText().equals("0")) {
                jcb_paciente1.setSelectedItem("SELEIONE O PACIENTE");
                jcb_medico1.setSelectedItem("SELEIONE O MÉDICO");
            } else {
                medico = medicoCtrl.retoMedicoIdCtrl(Integer.parseInt(lbl_medico1.getText()));
                jcb_medico1.setSelectedItem(medico.getNome().toUpperCase());
                paciente = pacienteCtrl.retoPacienteIdCtrl(Integer.parseInt(lbl_paciente1.getText()));
                jcb_paciente1.setSelectedItem(paciente.getNome().toUpperCase());
            }
        }
    }//GEN-LAST:event_btn_realizarConsActionPerformed

    private void habilitarDesabilitar2(boolean condicao) {
        jcb_paciente1.setEnabled(condicao);
        jcb_medico1.setEnabled(condicao);
        txt_sistolica.setEnabled(condicao);
        txt_diastolica.setEnabled(condicao);
        txt_frequencia.setEnabled(condicao);
        btn_salvar1.setEnabled(condicao);
        jcb_dateTime.setEnabled(condicao);
    }

    private void preencherCod2() {
        if (jcb_paciente1.getItemCount() == 0) {
            jcb_paciente1.setSelectedItem("SELECIONE O PACIENTE");
            jcb_medico1.setSelectedItem("SELECIONE O MÉDICO");
        } else {
            paciente = pacienteCtrl.retoPacienteNomeCtrl(jcb_paciente1.getSelectedItem().toString());
            lbl_paciente1.setText(String.valueOf(paciente.getIdPaciente()));
            medico = medicoCtrl.retoMedicoNomeCtrl(jcb_medico1.getSelectedItem().toString());
            lbl_medico1.setText(String.valueOf(medico.getIdMedico()));
        }
    }

    private void selectConsulta() {
        salvarAlterar = "alterar";
        int linha = jt_consulta.getSelectedRow();
        int codigo = (int) jt_consulta.getValueAt(linha, 0);
        try {
            consulta = consultaCtrl.getConsultaIdCtrl(codigo);
            lbl_cosulta.setText(String.valueOf(consulta.getId_consulta()));
            lbl_paciente1.setText(String.valueOf(consulta.getPaciente()));
            lbl_medico1.setText(String.valueOf(consulta.getMedico()));
            txt_sistolica.setText(String.valueOf(consulta.getSistolica()));
            txt_diastolica.setText(String.valueOf(consulta.getDiastolica()));
            txt_frequencia.setText(consulta.getFrequencia());
            if (jcb_dateTime.getText().equals("  /  /       :  ")) {
                jcb_dateTime.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date(System.currentTimeMillis())));
            } else {
                jcb_dateTime.setText(consulta.getData_consulta());
            }
            jcb_realiza.setSelectedItem(consulta.getStatus());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar registro!", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void retornarAgendaCons() {
        salvarAlterar = "salvar";
        int linha = jt_agenda.getSelectedRow();
        int codigo = (int) jt_agenda.getValueAt(linha, 0);
        try {
            agenda = agendaCtrl.getAgendaController(codigo);
            lbl_cosulta.setText(String.valueOf(agenda.getId_agenda()));
            lbl_paciente1.setText(String.valueOf(agenda.getPaciente()));
            lbl_medico1.setText(String.valueOf(agenda.getMedico()));
            if (jcb_dateTime.getText().equals("  /  /       :  ")) {
                jcb_dateTime.setText(new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date(System.currentTimeMillis())));
            } else {
                jcb_dateTime.setText(agenda.getDataAgenda().toString());
            }
            jcb_realiza.setSelectedItem(agenda.getStatus());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar registro!", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterarAgenda() {
        if (jDateChooserData.getDate() == null || txt_hora.getText().equals("  :  ") || jcb_realizada.getSelectedItem().equals("SELECIONE") || txt_motivo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos campos!", "AVISO", JOptionPane.ERROR_MESSAGE);
        } else {
            agenda.setMedico(Integer.parseInt(lbl_medico.getText()));
            agenda.setPaciente(Integer.parseInt(lbl_paciente.getText()));
            agenda.setDataAgenda(jDateChooserData.getDate());
            agenda.setHoraAagenda(txt_hora.getText());
            agenda.setMotivoConsulta(txt_motivo.getText().toUpperCase());
            agenda.setStatus(jcb_realizada.getSelectedItem().toString());

            if (agendaCtrl.upAgendaCtrl(agenda)) {
                JOptionPane.showMessageDialog(null, "Alterado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                habilitarDesabilitar(false);
                jcb_realizada.setEnabled(false);
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar alterar registro!", "AVISO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void preencherCod() {
        if (jcb_paciente.getItemCount() == 0) {
            jcb_paciente.setSelectedItem("SELECIONE O PACIENTE");
            jcb_medico.setSelectedItem("SELECIONE O MÉDICO");
        } else {
            paciente = pacienteCtrl.retoPacienteNomeCtrl(jcb_paciente.getSelectedItem().toString());
            lbl_paciente.setText(String.valueOf(paciente.getIdPaciente()));
            medico = medicoCtrl.retoMedicoNomeCtrl(jcb_medico.getSelectedItem().toString());
            lbl_medico.setText(String.valueOf(medico.getIdMedico()));
        }
    }

    private void selectAgendaCons() {
        salvarAlterar = "alterar";
        int linha = jt_agenda.getSelectedRow();
        int codigo = (int) jt_agenda.getValueAt(linha, 0);
        try {
            agenda = agendaCtrl.getAgendaController(codigo);
            lbl_agenda.setText(String.valueOf(agenda.getId_agenda()));
            lbl_paciente.setText(String.valueOf(agenda.getPaciente()));
            lbl_medico.setText(String.valueOf(agenda.getMedico()));
            txt_hora.setText(agenda.getHoraAagenda());
            txt_motivo.setText(agenda.getMotivoConsulta());
            jDateChooserData.setDate(agenda.getDataAgenda());
            jcb_realizada.setSelectedItem(agenda.getStatus());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar registro!", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarAgenda() {
        DefaultTableModel modelo = (DefaultTableModel) jt_agenda.getModel();
        listaAgendaMedPac = genericCtrl.getListaAgendaCtrl();
        int cont = listaAgendaMedPac.size();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaAgendaMedPac.get(i).getAgenda().getId_agenda(),
                listaAgendaMedPac.get(i).getPaciente().getNome(),
                listaAgendaMedPac.get(i).getMedico().getNome(),
                formato.format(listaAgendaMedPac.get(i).getAgenda().getDataAgenda()),
                listaAgendaMedPac.get(i).getAgenda().getHoraAagenda(),
                listaAgendaMedPac.get(i).getAgenda().getMotivoConsulta(),
                listaAgendaMedPac.get(i).getAgenda().getStatus()
            });
        }
        corNaLinha2();
    }

    private void limparTable() {
        DefaultTableModel modelo = (DefaultTableModel) jt_agenda.getModel();
        modelo.setNumRows(0);
    }

    private void retornarPaciente() {
        if (jcb_paciente.getItemCount() == 0) {
            jcb_paciente.setSelectedItem("Selecione o paciente");
        } else {
            paciente = pacienteCtrl.retoPacienteNomeCtrl(jcb_paciente.getSelectedItem().toString());
            lbl_paciente.setText(String.valueOf(paciente.getIdPaciente()));
        }
    }

    private void carregarPacientes() {
        listarPaciente = pacienteCtrl.retoListPacienteCrtl();
        jcb_paciente1.removeAllItems();
        for (int i = 0; i < listarPaciente.size(); i++) {
            jcb_paciente1.addItem(listarPaciente.get(i).getNome());
        }
    }

    private void carregarPaciente() {
        listarPaciente = pacienteCtrl.retoListPacienteCrtl();
        jcb_paciente.removeAllItems();
        for (int i = 0; i < listarPaciente.size(); i++) {
            jcb_paciente.addItem(listarPaciente.get(i).getNome());
        }
    }

    private void retornarMedico() {
        if (jcb_medico.getItemCount() == 0) {
            jcb_medico.setSelectedItem("Selecione o médico");
        } else {
            medico = medicoCtrl.retoMedicoNomeCtrl(jcb_medico.getSelectedItem().toString());
            lbl_medico.setText(String.valueOf(medico.getIdMedico()));
        }
    }

    private void carregarMedicos() {
        listarMedico = medicoCtrl.retoListMedicoCrtl();
        jcb_medico1.removeAllItems();
        for (int i = 0; i < listarMedico.size(); i++) {
            jcb_medico1.addItem(listarMedico.get(i).getNome());
        }
    }

    private void carregarMedico() {
        listarMedico = medicoCtrl.retoListMedicoCrtl();
        jcb_medico.removeAllItems();
        for (int i = 0; i < listarMedico.size(); i++) {
            jcb_medico.addItem(listarMedico.get(i).getNome());
        }
    }

    private void salvarAgenda() {
        if (jDateChooserData.getDate() == null || txt_hora.getText().equals("  :  ") || jcb_realizada.getSelectedItem().equals("SELECIONE") || txt_motivo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos campos!", "AVISO", JOptionPane.ERROR_MESSAGE);
        } else {
            agenda.setDataAgenda(jDateChooserData.getDate());
            agenda.setHoraAagenda(txt_hora.getText());
            agenda.setMotivoConsulta(txt_motivo.getText());
            agenda.setMedico(Integer.parseInt(lbl_medico.getText()));
            agenda.setPaciente(Integer.parseInt(lbl_paciente.getText()));
            agenda.setStatus(jcb_realizada.getSelectedItem().toString());

            if (agendaCtrl.saveAgendaCrtl(agenda) > 0) {
                JOptionPane.showMessageDialog(rootPane, "Salvo com Sucesso!", "SUCEESO", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar Cadastrar!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void limparCampos() {
        jcb_paciente.setSelectedIndex(0);
        jcb_medico.setSelectedIndex(0);
        pegarDataHoraSistema();
        txt_motivo.setText("");
        jcb_realizada.setSelectedIndex(0);
        jcb_paciente.setSelectedIndex(0);
        jcb_medico.setSelectedIndex(0);
    }

    private void limparCampos2() {
        jcb_paciente1.setSelectedIndex(0);
        jcb_medico1.setSelectedIndex(0);
        txt_sistolica.setText("");
        txt_diastolica.setText("");
        txt_frequencia.setText("");
        jcb_realiza.setSelectedIndex(0);

    }

    private void retornarPacientes() {
        if (jcb_paciente1.getItemCount() == 0) {
            jcb_paciente1.setSelectedItem("Selecione o paciente");
        } else {
            paciente = pacienteCtrl.retoPacienteNomeCtrl(jcb_paciente.getSelectedItem().toString());
            lbl_paciente1.setText(String.valueOf(paciente.getIdPaciente()));
        }
    }

    private void retornarMedicos() {
        if (jcb_medico1.getItemCount() == 0) {
            jcb_medico1.setSelectedItem("Selecione o médico");
        } else {
            medico = medicoCtrl.retoMedicoNomeCtrl(jcb_medico.getSelectedItem().toString());
            lbl_medico1.setText(String.valueOf(medico.getIdMedico()));
        }
    }

    private void habilitarDesabilitar(boolean condicao) {
        btn_salvar.setEnabled(condicao);
        jcb_paciente.setEnabled(condicao);
        jcb_medico.setEnabled(condicao);
        jDateChooserData.setEnabled(condicao);
        txt_hora.setEnabled(condicao);
        txt_motivo.setEnabled(condicao);
        jcb_realizada.setEnabled(condicao);
    }

    private void pegarDataHoraSistema() {
        jDateChooserData.setDate(new Date(System.currentTimeMillis()));
        txt_hora.setText(new SimpleDateFormat("HH:mm").format(new Time(System.currentTimeMillis())));
    }

    public void corNaLinha2() {
        String status2 = new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis()));
        String status = "NÃO";
        jt_agenda.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable tabela, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(tabela, value, isSelected, hasFocus, row, column);
                Color c = Color.WHITE;
                Font f;
                Object texto = tabela.getValueAt(row, 3);
                Object texto2 = tabela.getValueAt(row, 6);
                if (status2.compareTo((String) texto) > 0) {
                    c = Color.RED;
                }
                if (texto2 != null && "SIM".equals(texto2.toString())) {
                    c = Color.CYAN;
                }
                label.setBackground(c);
                if (texto != null && status.equals(texto2.toString())) {
                    f = new Font("Arial", Font.BOLD, 12);
                    label.setFont(f);
                }
                jt_agenda.setSelectionForeground(Color.BLACK);

                return label;
            }
        });
    }

    private void carregarConsulta() {
        DefaultTableModel modelo = (DefaultTableModel) jt_consulta.getModel();
        listaConsultaMedPac = genericCtrl.getListaConsultaCtrl();
        int cont = listaConsultaMedPac.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaConsultaMedPac.get(i).getConsulta().getId_consulta(),
                listaConsultaMedPac.get(i).getPaciente().getNome(),
                listaConsultaMedPac.get(i).getMedico().getNome(),
                listaConsultaMedPac.get(i).getConsulta().getSistolica(),
                listaConsultaMedPac.get(i).getConsulta().getDiastolica(),
                listaConsultaMedPac.get(i).getConsulta().getFrequencia(),
                listaConsultaMedPac.get(i).getConsulta().getData_consulta(),
                listaConsultaMedPac.get(i).getConsulta().getStatus()
            });
        }
        CorDataLinha();
    }

    private void CorDataLinha() {
        String status = "SIM";
        String status2 = "NÃO";
        jt_consulta.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable tabela, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(tabela, value, isSelected, hasFocus, row, column);
                Color c = Color.WHITE;
                Font f;
                Object texto = tabela.getValueAt(row, 7);
                if (texto != null && status.equals(texto.toString())) {
                    c = Color.CYAN;
                }
                label.setBackground(c);
                if (texto != null && status2.equals(texto.toString())) {
                    f = new Font("Arial", Font.BOLD, 12);
                    label.setFont(f);
                }
                jt_consulta.setSelectionForeground(Color.BLACK);

                return label;
            }
        });
    }

    private void salvar() {
        salvarAlterar = "salvar";
        if (jcb_paciente.getSelectedItem().toString().equals("") || jcb_medico.getSelectedItem().toString().equals("") || txt_sistolica.getText().equals("") || txt_diastolica.getText().equals("") || txt_frequencia.getText().trim().equals("") || jcb_dateTime.getText().equals("  /  /       :  ") || jcb_realiza.getSelectedItem().equals("SELECIONE")) {
            JOptionPane.showMessageDialog(null, "Preencha todos campos!", "AVISO", JOptionPane.ERROR_MESSAGE);
        } else {
            consulta.setPaciente(Integer.parseInt(lbl_paciente1.getText()));
            consulta.setMedico(Integer.parseInt(lbl_medico1.getText()));
            consulta.setSistolica(Integer.parseInt(txt_sistolica.getText()));
            consulta.setDiastolica(Integer.parseInt(txt_diastolica.getText()));
            consulta.setFrequencia(txt_frequencia.getText());
            consulta.setData_consulta(jcb_dateTime.getText());
            consulta.setStatus(jcb_realiza.getSelectedItem().toString());
            agenda.setStatus(jcb_realiza.getSelectedItem().toString());

            if (consultaCtrl.saveConsultaCrtl(consulta) > 0 && agendaCtrl.upAgendaCtrl(agenda)) {
                JOptionPane.showMessageDialog(null, "Salvo com Sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                habilitarDesabilitar2(false);
                limparCampos2();
                limparTabela2();
                limparTable();
                carregarConsulta();
                carregarAgenda();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar Cadastrar!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void alterarConsulta() {
        salvarAlterar = "alterar";
        if (jcb_paciente.getSelectedItem().toString().equals("") || jcb_medico.getSelectedItem().toString().equals("") || txt_sistolica.getText().equals("") || txt_diastolica.getText().equals("") || txt_frequencia.getText().trim().equals("") || jcb_dateTime.getText().equals("  /  /       :  ") || jcb_realiza.getSelectedItem().equals("SELECIONE")) {
            JOptionPane.showMessageDialog(null, "Preencha todos campos!", "AVISO", JOptionPane.ERROR_MESSAGE);
        } else {
            consulta.setPaciente(Integer.parseInt(lbl_paciente1.getText()));
            consulta.setMedico(Integer.parseInt(lbl_medico1.getText()));
            consulta.setStatus(jcb_realiza.getSelectedItem().toString());
            consulta.setSistolica(Integer.parseInt(txt_sistolica.getText()));
            consulta.setDiastolica(Integer.parseInt(txt_diastolica.getText()));
            consulta.setFrequencia(txt_frequencia.getText());
            consulta.setData_consulta(jcb_dateTime.getText());

            if (consultaCtrl.upConsultCtrl(consulta)) {
                JOptionPane.showMessageDialog(null, "Alterado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                habilitarDesabilitar2(false);
                limparCampos2();
                limparTabela2();
                carregarConsulta();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar alterar registro!", "AVISO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void limparTabela2() {
        DefaultTableModel modelo = (DefaultTableModel) jt_consulta.getModel();
        modelo.setNumRows(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_editar1;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_fechar1;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_novo1;
    private javax.swing.JButton btn_realizarCons;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_salvar1;
    private com.toedter.calendar.JDateChooser jDateChooserData;
    private javax.swing.JDialog jDialogConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JFormattedTextField jcb_dateTime;
    private componentes.UJComboBox jcb_medico;
    private componentes.UJComboBox jcb_medico1;
    private componentes.UJComboBox jcb_paciente;
    private componentes.UJComboBox jcb_paciente1;
    private javax.swing.JComboBox<String> jcb_realiza;
    private javax.swing.JComboBox<String> jcb_realizada;
    private javax.swing.JTable jt_agenda;
    private javax.swing.JTable jt_consulta;
    private javax.swing.JLabel lbl_agenda;
    private javax.swing.JLabel lbl_cosulta;
    private javax.swing.JLabel lbl_medico;
    private javax.swing.JLabel lbl_medico1;
    private javax.swing.JLabel lbl_paciente;
    private javax.swing.JLabel lbl_paciente1;
    private javax.swing.JFormattedTextField txt_diastolica;
    private javax.swing.JTextField txt_frequencia;
    private javax.swing.JFormattedTextField txt_hora;
    private javax.swing.JTextArea txt_motivo;
    private javax.swing.JFormattedTextField txt_sistolica;
    // End of variables declaration//GEN-END:variables
}
