/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PacienteCtrl;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Paciente;
import util.CPF;
import util.FormatarDatas;

/**
 *
 * @author leogo
 */
public class CadastroPacienteView extends javax.swing.JInternalFrame {

    FormatarDatas datas = new FormatarDatas();
    Paciente paciente = new Paciente();
    PacienteCtrl pacienteCtrl = new PacienteCtrl();

    /**
     * Creates new form CadastroPacienteView
     */
    public CadastroPacienteView() {
        initComponents();
        habilitarDesabiliar(false);
        erroJlInvisible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_rg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_data = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jcb_sexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_peso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        jl_erro1 = new javax.swing.JLabel();
        jl_erro2 = new javax.swing.JLabel();
        jl_erro3 = new javax.swing.JLabel();
        jl_erro4 = new javax.swing.JLabel();
        jl_erro5 = new javax.swing.JLabel();
        jl_erro6 = new javax.swing.JLabel();
        jl_erro7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_end = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_cep = new javax.swing.JFormattedTextField();
        txt_numero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcb_estado = new javax.swing.JComboBox<>();
        txt_tel_celular = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jl_erro8 = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        brn_novo = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Paciente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nome");

        txt_nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("CPF");

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("RG");

        txt_rg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Data de Nascimento");

        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Sexo");

        jcb_sexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO - M", "FEMININO - F" }));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Peso kg");

        txt_peso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_peso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_pesoFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Altura ");

        txt_altura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_altura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_alturaFocusLost(evt);
            }
        });

        jl_erro1.setText("*");

        jl_erro2.setText("*");

        jl_erro3.setText("*");

        jl_erro4.setText("*");

        jl_erro5.setText("*");

        jl_erro6.setText("*");

        jl_erro7.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_erro4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addComponent(jl_erro5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(2, 2, 2)
                                .addComponent(jl_erro6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_erro7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_altura)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(jl_erro1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_erro2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_erro3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jl_erro1)
                    .addComponent(jl_erro2)
                    .addComponent(jl_erro3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jl_erro4)
                    .addComponent(jl_erro5)
                    .addComponent(jl_erro6)
                    .addComponent(jl_erro7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço e Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Endereço");

        txt_end.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Bairro");

        txt_bairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("CEP");

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_numero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Número");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Estado");

        jcb_estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACRE - AC", "ALAGOAS - AL", "AMAPÁ - AP", "AMAZONAS - AM", "BAHIA  - BA", "CEARÁ - CE", "DISTRITO FEDERAL  - DF", "ESPÍRITO SANTO - ES", "GOIÁS - GO", "MARANHÃO - MA", "MATO GROSSO - MT", "MATO GROSSO DO SUL - MS", "MINAS GERAIS - MG", "PARÁ - PA", "PARAÍBA - PB", "PARANÁ - PR", "PERNAMBUCO - PE", "PIAUÍ - PI", "RIO DE JANEIRO - RJ", "RIO GRANDE DO NORTE - RN", "RIO GRANDE DO SUL - RS", "RONDÔNIA - RO", "RORAIMA - RR", "SANTA CATARINA - SC", "SÃO PAULO - SP", "SERGIPE - SE", "TOCANTINS - TO", " " }));

        try {
            txt_tel_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel_celular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Tel. Celular");

        txt_cidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel14.setText("Cidade");

        jl_erro8.setText("*");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(txt_end)
                    .addComponent(jLabel12)
                    .addComponent(jcb_estado, 0, 174, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(txt_bairro)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 92, Short.MAX_VALUE))
                            .addComponent(txt_numero)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_erro8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jl_erro8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_24px.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        brn_novo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        brn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Create_24px.png"))); // NOI18N
        brn_novo.setText("Novo");
        brn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_novoActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_fechar)
                        .addGap(18, 18, 18)
                        .addComponent(brn_novo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(brn_novo)
                    .addComponent(btn_fechar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(270, 100, 754, 427);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void brn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_novoActionPerformed
        habilitarDesabiliar(true);
        txt_nome.requestFocus();
    }//GEN-LAST:event_brn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        if (txt_nome.getText().trim().equals("") || txt_cpf.getText().equals("") || txt_rg.getText().trim().equals("") || jcb_sexo.getSelectedItem().equals("") || txt_data.getText().equals("  /  /    ") || txt_tel_celular.getText().equals("") || txt_peso.getText().trim().equals("") || txt_altura.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos obrigatórios", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            erroJlVisible();
            resetErroBorderLine();
        } else {
            salvar();
            erroJlInvisible();
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_pesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pesoFocusLost
        try {
            String sv = txt_peso.getText();
            String vsf = sv.replace(" ", "").replace(".", "").replace(",", ".");
            Double valor = new Double(vsf);
            txt_peso.setText(String.valueOf(valor));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_pesoFocusLost

    private void txt_alturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alturaFocusLost
        try {
            String sv = txt_altura.getText();
            String vsf = sv.replace(" ", "").replace(".", "").replace(",", ".");
            Double valor = new Double(vsf);
            txt_altura.setText(String.valueOf(valor));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_alturaFocusLost

    private void erroJlInvisible() {
        jl_erro1.setVisible(false);
        jl_erro2.setVisible(false);
        jl_erro3.setVisible(false);
        jl_erro4.setVisible(false);
        jl_erro5.setVisible(false);
        jl_erro6.setVisible(false);
        jl_erro7.setVisible(false);
        jl_erro8.setVisible(false);
    }

    private void erroJlVisible() {
        jl_erro1.setVisible(true);
        jl_erro2.setVisible(true);
        jl_erro3.setVisible(true);
        jl_erro4.setVisible(true);
        jl_erro5.setVisible(true);
        jl_erro6.setVisible(true);
        jl_erro7.setVisible(true);
        jl_erro8.setVisible(true);

    }

    private void resetErroBorderLine() {
        jl_erro1.setForeground(Color.red);
        jl_erro2.setForeground(Color.red);
        jl_erro3.setForeground(Color.red);
        jl_erro4.setForeground(Color.red);
        jl_erro5.setForeground(Color.red);
        jl_erro6.setForeground(Color.red);
        jl_erro7.setForeground(Color.red);
        jl_erro8.setForeground(Color.red);
    }

    private void salvar() {
        paciente.setNome(txt_nome.getText().toUpperCase());
        CPF pf = new CPF(txt_cpf.getText());
        paciente.setCpf(txt_cpf.getText().replaceAll("[.-]", ""));
        paciente.setRg(txt_rg.getText());
        try {
            paciente.setDataNascimento(datas.converterDataStringParaDate(txt_data.getText()));
        } catch (Exception ex) {
            Logger.getLogger(CadastroPacienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
        paciente.setSexo(jcb_sexo.getSelectedItem().toString());
        paciente.setPeso(Double.parseDouble(txt_peso.getText()));
        paciente.setAltura(Double.parseDouble(txt_altura.getText()));
        paciente.setEndereco(txt_end.getText().toUpperCase());
        paciente.setBairro(txt_bairro.getText().toUpperCase());
        paciente.setCep(txt_cep.getText());
        paciente.setNumero(txt_numero.getText());
        paciente.setEstadoUf(jcb_estado.getSelectedItem().toString());
        paciente.setCidade(txt_cidade.getText().toUpperCase());
        paciente.setTelCelular(txt_tel_celular.getText());

        if (pf.isCPF() || pf.equals("   .   .   -  ")) {
            if (pacienteCtrl.savePacienteCrtl(paciente) > 0) {
                JOptionPane.showMessageDialog(rootPane, "Salvo com Sucesso!", "SUCEESO", JOptionPane.INFORMATION_MESSAGE);
                habilitarDesabiliar(false);
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Cadastrar!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void habilitarDesabiliar(boolean condicao) {
        txt_nome.setEnabled(condicao);
        txt_cpf.setEnabled(condicao);
        txt_rg.setEnabled(condicao);
        txt_data.setEnabled(condicao);
        jcb_sexo.setEnabled(condicao);
        txt_peso.setEnabled(condicao);
        txt_altura.setEnabled(condicao);
        txt_end.setEnabled(condicao);
        txt_bairro.setEnabled(condicao);
        txt_cep.setEnabled(condicao);
        txt_numero.setEnabled(condicao);
        jcb_estado.setEnabled(condicao);
        txt_cidade.setEnabled(condicao);
        txt_numero.setEnabled(condicao);
        txt_tel_celular.setEnabled(condicao);

        btn_salvar.setEnabled(condicao);
    }

    private void limparCampos() {
        txt_nome.setText("");
        txt_cpf.setText("");
        txt_rg.setText("");
        txt_data.setText("");
        jcb_sexo.setSelectedIndex(0);
        txt_peso.setText("");
        txt_altura.setText("");
        txt_end.setText("");
        txt_bairro.setText("");
        txt_cep.setText("");
        txt_numero.setText("");
        jcb_estado.setSelectedIndex(0);
        txt_cidade.setText("");
        txt_numero.setText("");
        txt_tel_celular.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_novo;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcb_estado;
    private javax.swing.JComboBox<String> jcb_sexo;
    private javax.swing.JLabel jl_erro1;
    private javax.swing.JLabel jl_erro2;
    private javax.swing.JLabel jl_erro3;
    private javax.swing.JLabel jl_erro4;
    private javax.swing.JLabel jl_erro5;
    private javax.swing.JLabel jl_erro6;
    private javax.swing.JLabel jl_erro7;
    private javax.swing.JLabel jl_erro8;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JFormattedTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_end;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JFormattedTextField txt_tel_celular;
    // End of variables declaration//GEN-END:variables
}
