/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.CPF;
import controller.MedicoCtrl;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Medico;
import util.FormatarDatas;

/**
 *
 * @author leogo
 */
public class CadastroMedicoView extends javax.swing.JInternalFrame {

    FormatarDatas datas = new FormatarDatas();
    Medico medico = new Medico();
    MedicoCtrl medicoCtrl = new MedicoCtrl();
    ArrayList<Medico> listarMedico = new ArrayList<>();
    String salvarAlterar;

    /**
     * Creates new form CadastroMedicoView
     */
    public CadastroMedicoView() {
        initComponents();
        btn_novo_acesso.setEnabled(false);
        carregarMedico();
        preencherMedicoComboBox();
        erroJlInvisible();
        habilitarDesabiliar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogo_Menu = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txt_codigoDialog = new javax.swing.JTextField();
        jcb_medicoDialog = new componentes.UJComboBox();
        jLabel21 = new javax.swing.JLabel();
        jcb_permissaoDialog = new componentes.UJComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_usuarioDialog = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_senhaDialog = new javax.swing.JPasswordField();
        txt_conf_senhaDialog = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btn_cancelarDialog = new javax.swing.JButton();
        btn_salvarDialog = new javax.swing.JButton();
        btn_novoDialog = new javax.swing.JButton();
        jPanelFormMedico = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        jcb_sexo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_data = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jcb_civil = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_rg = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_emissor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_end = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        txt_cep = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        jcb_estado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txt_tel_resid = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tel_celular = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jl_Error = new javax.swing.JLabel();
        jl_Error1 = new javax.swing.JLabel();
        jl_Error2 = new javax.swing.JLabel();
        jl_Error3 = new javax.swing.JLabel();
        jl_Error4 = new javax.swing.JLabel();
        jl_Error5 = new javax.swing.JLabel();
        jl_Error6 = new javax.swing.JLabel();
        jl_Error7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_num_conselho = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_espc_princ = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_atuacao = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_espc_secund = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_tel_comerc = new javax.swing.JFormattedTextField();
        jl_Error8 = new javax.swing.JLabel();
        jl_Error9 = new javax.swing.JLabel();
        jl_Error10 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_novo_acesso = new javax.swing.JButton();

        jDialogo_Menu.setTitle("Cadastro de Usuário");
        jDialogo_Menu.setBackground(new java.awt.Color(255, 255, 255));
        jDialogo_Menu.setBounds(new java.awt.Rectangle(300, 200, 635, 245));
        jDialogo_Menu.setResizable(false);
        jDialogo_Menu.setType(java.awt.Window.Type.POPUP);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txt_codigoDialog.setEditable(false);
        txt_codigoDialog.setBackground(new java.awt.Color(204, 204, 204));

        jcb_medicoDialog.setMaximumRowCount(10);
        jcb_medicoDialog.setToolTipText("");
        jcb_medicoDialog.setAutocompletar(true);
        jcb_medicoDialog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_medicoDialog.setMinimumSize(new java.awt.Dimension(126, 25));
        jcb_medicoDialog.setPreferredSize(new java.awt.Dimension(126, 26));
        jcb_medicoDialog.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcb_medicoDialogPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Nome do Médico");

        jcb_permissaoDialog.setEditable(true);
        jcb_permissaoDialog.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Comum" }));
        jcb_permissaoDialog.setAutocompletar(true);
        jcb_permissaoDialog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Permissão");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Código");

        txt_usuarioDialog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Senha");

        txt_senhaDialog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_conf_senhaDialog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Confirmar Senha");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Usuário");

        btn_cancelarDialog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_cancelarDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_cancelarDialog.setText("Fechar");
        btn_cancelarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarDialogActionPerformed(evt);
            }
        });

        btn_salvarDialog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_salvarDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_24px.png"))); // NOI18N
        btn_salvarDialog.setText("Salvar");
        btn_salvarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarDialogActionPerformed(evt);
            }
        });

        btn_novoDialog.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_novoDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Create_24px.png"))); // NOI18N
        btn_novoDialog.setText("Novo");
        btn_novoDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigoDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_medicoDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jcb_permissaoDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_usuarioDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_senhaDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_conf_senhaDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelarDialog)
                .addGap(18, 18, 18)
                .addComponent(btn_novoDialog)
                .addGap(18, 18, 18)
                .addComponent(btn_salvarDialog)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigoDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_medicoDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_permissaoDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_conf_senhaDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_senhaDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_usuarioDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvarDialog)
                    .addComponent(btn_cancelarDialog)
                    .addComponent(btn_novoDialog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogo_MenuLayout = new javax.swing.GroupLayout(jDialogo_Menu.getContentPane());
        jDialogo_Menu.getContentPane().setLayout(jDialogo_MenuLayout);
        jDialogo_MenuLayout.setHorizontalGroup(
            jDialogo_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogo_MenuLayout.setVerticalGroup(
            jDialogo_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Médico");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelFormMedico.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessois", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        txt_nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nome Completo");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("CPF");

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jcb_sexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO - M", "FEMININO - F" }));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Sexo");

        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Data de Nascimento");

        jcb_civil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_civil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTEIRO(A)", "CASADO(A)", "VIÚVO(A)", "DIVORCIADO(A)", " " }));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Estado Civil");

        jLabel7.setText("RG");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Órgão Emissor");

        txt_emissor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel9.setText("Endereço");

        jLabel10.setText("Número");

        jLabel11.setText("Bairro");

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("CEP");

        jLabel13.setText("Cidade");

        jcb_estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACRE - AC", "ALAGOAS - AL", "AMAPÁ - AP", "AMAZONAS - AM", "BAHIA  - BA", "CEARÁ - CE", "DISTRITO FEDERAL  - DF", "ESPÍRITO SANTO - ES", "GOIÁS - GO", "MARANHÃO - MA", "MATO GROSSO - MT", "MATO GROSSO DO SUL - MS", "MINAS GERAIS - MG", "PARÁ - PA", "PARAÍBA - PB", "PARANÁ - PR", "PERNAMBUCO - PE", "PIAUÍ - PI", "RIO DE JANEIRO - RJ", "RIO GRANDE DO NORTE - RN", "RIO GRANDE DO SUL - RS", "RONDÔNIA - RO", "RORAIMA - RR", "SANTA CATARINA - SC", "SÃO PAULO - SP", "SERGIPE - SE", "TOCANTINS - TO", " " }));
        jcb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_estadoActionPerformed(evt);
            }
        });

        jLabel14.setText("Estado UF");

        try {
            txt_tel_resid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel_resid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel15.setText("Telefone Residencial");

        try {
            txt_tel_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel_celular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel16.setText("Telefone Celular");

        jl_Error.setText("*");

        jl_Error1.setText("*");

        jl_Error2.setText("*");

        jl_Error3.setText("*");

        jl_Error4.setText("*");

        jl_Error5.setText("*");

        jl_Error6.setText("*");

        jl_Error7.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_Error4))
                            .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_Error5)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jcb_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_end)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel11)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel12)
                                .addGap(151, 151, 151)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(143, 143, 143)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_Error6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error))
                                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error1)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error2)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(txt_emissor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tel_resid, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(txt_tel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_Error7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(txt_cidade)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jl_Error))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jl_Error1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jl_Error2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jl_Error3)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jl_Error4))
                            .addGap(5, 5, 5)
                            .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jl_Error5))
                            .addGap(5, 5, 5)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(5, 5, 5)
                            .addComponent(jcb_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(txt_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jl_Error6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jl_Error7)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tel_resid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_tel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Profissionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Número do Conselho");

        txt_num_conselho.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Especialidade Principal");

        txt_espc_princ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Email Comercial");

        txt_email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Área de Atuação");

        txt_atuacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Especialidade Secudária (opcional)");

        txt_espc_secund.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Telefone Comercial (opcional)");

        try {
            txt_tel_comerc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel_comerc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jl_Error8.setText("*");

        jl_Error9.setText("*");

        jl_Error10.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_atuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(3, 3, 3)
                                .addComponent(jl_Error10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_tel_comerc)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_num_conselho, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(4, 4, 4)
                                .addComponent(jl_Error8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(5, 5, 5)
                                .addComponent(jl_Error9))
                            .addComponent(txt_espc_princ, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_espc_secund))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jl_Error8)
                    .addComponent(jl_Error9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_num_conselho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_espc_princ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_espc_secund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jl_Error10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_atuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel_comerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_cancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_cancelar.setText("Fechar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Create_24px.png"))); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_24px.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_novo_acesso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_novo_acesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Access_24px.png"))); // NOI18N
        btn_novo_acesso.setText("Cadastrar Acesso");
        btn_novo_acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo_acessoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormMedicoLayout = new javax.swing.GroupLayout(jPanelFormMedico);
        jPanelFormMedico.setLayout(jPanelFormMedicoLayout);
        jPanelFormMedicoLayout.setHorizontalGroup(
            jPanelFormMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFormMedicoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_novo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_novo_acesso)))
                .addContainerGap())
        );
        jPanelFormMedicoLayout.setVerticalGroup(
            jPanelFormMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFormMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_novo)
                    .addComponent(btn_salvar)
                    .addComponent(btn_novo_acesso))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFormMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFormMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(250, 50, 732, 556);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void preencherMedicoComboBox() {
        if (jcb_medicoDialog.getItemCount() == 0) {
            jcb_medicoDialog.setSelectedItem("Sem Registro");
        } else {
            medico = medicoCtrl.retoMedicoNomeCtrl(jcb_medicoDialog.getSelectedItem().toString());
            txt_codigoDialog.setText(String.valueOf(medico.getIdMedico()));
        }
    }

    private void carregarMedico() {
        listarMedico = medicoCtrl.retoListMedicoCrtl();
        jcb_medicoDialog.removeAllItems();
        for (int i = 0; i < listarMedico.size(); i++) {
            jcb_medicoDialog.addItem(listarMedico.get(i).getNome());
        }
    }

    private void erroJlVisible() {
        jl_Error.setVisible(true);
        jl_Error1.setVisible(true);
        jl_Error2.setVisible(true);
        jl_Error3.setVisible(true);
        jl_Error4.setVisible(true);
        jl_Error5.setVisible(true);
        jl_Error6.setVisible(true);
        jl_Error7.setVisible(true);
        jl_Error8.setVisible(true);
        jl_Error9.setVisible(true);
        jl_Error10.setVisible(true);
    }

    private void erroJlInvisible() {
        jl_Error.setVisible(false);
        jl_Error1.setVisible(false);
        jl_Error2.setVisible(false);
        jl_Error3.setVisible(false);
        jl_Error4.setVisible(false);
        jl_Error5.setVisible(false);
        jl_Error6.setVisible(false);
        jl_Error7.setVisible(false);
        jl_Error8.setVisible(false);
        jl_Error9.setVisible(false);
        jl_Error10.setVisible(false);
    }

    private void resetErroBorderLine() {
        jl_Error.setForeground(Color.red);
        jl_Error1.setForeground(Color.red);
        jl_Error2.setForeground(Color.red);
        jl_Error3.setForeground(Color.red);
        jl_Error4.setForeground(Color.red);
        jl_Error5.setForeground(Color.red);
        jl_Error6.setForeground(Color.red);
        jl_Error7.setForeground(Color.red);
        jl_Error8.setForeground(Color.red);
        jl_Error9.setForeground(Color.red);
        jl_Error10.setForeground(Color.red);
    }

    private void btn_cancelarDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarDialogActionPerformed
        jDialogo_Menu.dispose();
    }//GEN-LAST:event_btn_cancelarDialogActionPerformed

    private void jcb_medicoDialogPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcb_medicoDialogPopupMenuWillBecomeInvisible
        if (jcb_medicoDialog.isPopupVisible()) {
            try {
                String nome = (String) jcb_medicoDialog.getSelectedItem();

                //recuperar dados do banco
                medico = medicoCtrl.retoMedicoNomeCtrl(nome);

                //setar na interface
                if (txt_usuarioDialog.getText().equals("null") && txt_senhaDialog.getText().equals("null")) {
                    txt_usuarioDialog.setText("");
                    txt_senhaDialog.setText("");
                } else {
                    txt_usuarioDialog.setText(medico.getUsuario());
                    txt_senhaDialog.setText(medico.getSenha());
                }
                jcb_permissaoDialog.setSelectedItem(medico.getPermissao());
                jDialogo_Menu.setVisible(true);
                habilitarDesabiliar(true);
                preencherMedicoComboBox();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar usuário!", "AVISO", JOptionPane.ERROR_MESSAGE);
                this.habilitarDesabiliar(false);
            }
        }
    }//GEN-LAST:event_jcb_medicoDialogPopupMenuWillBecomeInvisible

    private void btn_salvarDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarDialogActionPerformed
        if (!txt_conf_senhaDialog.getText().equals(txt_senhaDialog.getText())) {
            JOptionPane.showMessageDialog(null, "Senhas são diferentes", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } else if (txt_senhaDialog.getText().equals("") || txt_conf_senhaDialog.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Senhas devem ser preenchidas", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            alterarMedico();
        }
    }//GEN-LAST:event_btn_salvarDialogActionPerformed

    private void btn_novoDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoDialogActionPerformed
        carregarDadosMedico();
        habilitarDesabiliar(true);
    }//GEN-LAST:event_btn_novoDialogActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        salvarAlterar = "salvar";
        if (salvarAlterar.equals("salvar")) {
            if (txt_nome.getText().equals("") || txt_cpf.getText().equals("") || txt_rg.getText().equals("") || jcb_sexo.getSelectedItem().equals("") || txt_data.getText().equals("  /  /    ") || txt_tel_resid.getText().equals("") || txt_tel_celular.getText().equals("") || txt_num_conselho.getText().equals("") || txt_espc_princ.getText().equals("") || txt_atuacao.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Preencha os campos obrigatórios", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                erroJlVisible();
                resetErroBorderLine();
            } else {
                salvarMedico();
                erroJlInvisible();
            }
        } else if (salvarAlterar.equals("alterar")) {
            alterarMedico();
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        habilitarDesabiliar(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_novo_acessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo_acessoActionPerformed
        carregarMedico();
        preencherMedicoComboBox();
        jDialogo_Menu.setModal(true);
        jDialogo_Menu.setVisible(true);
    }//GEN-LAST:event_btn_novo_acessoActionPerformed

    private void jcb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_estadoActionPerformed

    private void carregarDadosMedico() {
        String nome = (String) jcb_medicoDialog.getSelectedItem();

        //recuperar dados do banco
        medico = medicoCtrl.retoMedicoNomeCtrl(nome);

        //setar na interface
        if (txt_usuarioDialog.getText().equals("null") && txt_senhaDialog.getText().equals("null")) {
            txt_usuarioDialog.setText("");
            txt_senhaDialog.setText("");
        } else {
            txt_usuarioDialog.setText(medico.getUsuario());
            txt_senhaDialog.setText(medico.getSenha());
        }
        jcb_permissaoDialog.setSelectedItem(medico.getPermissao());
        habilitarDesabiliar(true);
        preencherMedicoComboBox();
    }

    private void limparCampos() {
        txt_nome.setText("");
        txt_cpf.setText("");
        txt_rg.setText("");
        txt_emissor.setText("");
        jcb_sexo.setSelectedIndex(0);
        txt_data.setText("");
        jcb_civil.setSelectedIndex(0);
        txt_end.setText("");
        txt_num.setText("");
        txt_bairro.setText("");
        txt_cep.setText("");
        txt_cidade.setText("");
        jcb_estado.setSelectedItem(0);
        txt_tel_resid.setText("");
        txt_tel_celular.setText("");
        txt_num_conselho.setText("");
        txt_espc_princ.setText("");
        txt_espc_secund.setText("");
        txt_email.setText("");
        txt_atuacao.setText("");
        txt_tel_comerc.setText("");
    }

    private void alterarMedico() {
        medico.setUsuario(txt_usuarioDialog.getText().toUpperCase());
        medico.setPermissao(jcb_permissaoDialog.getSelectedItem().toString());
        medico.setSenha(txt_senhaDialog.getText().toUpperCase());

        if (medicoCtrl.updateMedicoCtrl(medico)) {
            JOptionPane.showMessageDialog(null, "Usuário Cadastrado!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            carregarMedico();
            habilitarDesabiliar(false);
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao Tentar Cadastrar", "ERRO", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void salvarMedico() {
        salvarAlterar = "salvar";
        medico.setNome(txt_nome.getText().toUpperCase());
        CPF pf = new CPF(txt_cpf.getText());
        medico.setCpf(txt_cpf.getText().replaceAll("[.-]", ""));
        medico.setRg(txt_rg.getText());
        medico.setCrm(txt_num_conselho.getText().toUpperCase());
        try {
            medico.setDataNasc(datas.converterDataStringParaDate(txt_data.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        medico.setSexo(String.valueOf(jcb_sexo.getSelectedItem()).toUpperCase());
        medico.setFuncao(txt_atuacao.getText().toUpperCase());
        medico.setOrgaoEmissor(txt_emissor.getText().toUpperCase());
        medico.setEstadoCivil(String.valueOf(jcb_civil.getSelectedItem()).toUpperCase());
        medico.setEndereco(txt_end.getText().toUpperCase());
        medico.setBairro(txt_bairro.getText().toUpperCase());
        medico.setCep(txt_cep.getText());
        medico.setNumero(txt_num.getText());
        medico.setCidade(txt_cidade.getText().toUpperCase());
        medico.setEstado(String.valueOf(jcb_estado.getSelectedItem()).toUpperCase());
        medico.setTelrrsid(txt_tel_resid.getText());
        medico.setTelCelular(txt_tel_celular.getText());
        medico.setEspcPrincipal(txt_espc_princ.getText().toUpperCase());
        medico.setEspcSecundaria(txt_espc_secund.getText().toUpperCase());
        medico.setEmailComerc(txt_email.getText().toUpperCase());
        medico.setTelComerc(txt_tel_comerc.getText());

        if (pf.isCPF() || pf.equals("   .   .   -  ")) {
            if (medicoCtrl.saveMedicoCrtl(medico) > 0) {
                JOptionPane.showMessageDialog(rootPane, "Salvo com Sucesso!", "SUCEESO", JOptionPane.INFORMATION_MESSAGE);
                btn_novo_acesso.setEnabled(true);
                habilitarDesabiliar(false);
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao Tentar Cadastrar!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void habilitarDesabiliar(boolean condicao) {
        txt_nome.setEnabled(condicao);
        txt_cpf.setEnabled(condicao);
        txt_rg.setEnabled(condicao);
        txt_emissor.setEnabled(condicao);
        jcb_sexo.setEnabled(condicao);
        txt_data.setEnabled(condicao);
        jcb_civil.setEnabled(condicao);
        txt_end.setEnabled(condicao);
        txt_num.setEnabled(condicao);
        txt_bairro.setEnabled(condicao);
        txt_cep.setEnabled(condicao);
        txt_cidade.setEnabled(condicao);
        jcb_estado.setEnabled(condicao);
        txt_tel_resid.setEnabled(condicao);
        txt_tel_celular.setEnabled(condicao);
        txt_num_conselho.setEnabled(condicao);
        txt_espc_princ.setEnabled(condicao);
        txt_espc_secund.setEnabled(condicao);
        txt_email.setEnabled(condicao);
        txt_atuacao.setEnabled(condicao);
        txt_tel_comerc.setEnabled(condicao);

        btn_salvar.setEnabled(condicao);

        txt_usuarioDialog.setEnabled(condicao);
        txt_senhaDialog.setEnabled(condicao);
        jcb_permissaoDialog.setEnabled(condicao);
        jcb_medicoDialog.setEnabled(condicao);
        txt_conf_senhaDialog.setEnabled(condicao);
        btn_salvarDialog.setEnabled(condicao);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelarDialog;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_novoDialog;
    private javax.swing.JButton btn_novo_acesso;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_salvarDialog;
    private javax.swing.JDialog jDialogo_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFormMedico;
    private javax.swing.JComboBox<String> jcb_civil;
    private javax.swing.JComboBox<String> jcb_estado;
    private componentes.UJComboBox jcb_medicoDialog;
    private componentes.UJComboBox jcb_permissaoDialog;
    private javax.swing.JComboBox<String> jcb_sexo;
    private javax.swing.JLabel jl_Error;
    private javax.swing.JLabel jl_Error1;
    private javax.swing.JLabel jl_Error10;
    private javax.swing.JLabel jl_Error2;
    private javax.swing.JLabel jl_Error3;
    private javax.swing.JLabel jl_Error4;
    private javax.swing.JLabel jl_Error5;
    private javax.swing.JLabel jl_Error6;
    private javax.swing.JLabel jl_Error7;
    private javax.swing.JLabel jl_Error8;
    private javax.swing.JLabel jl_Error9;
    private javax.swing.JTextField txt_atuacao;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JFormattedTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_codigoDialog;
    private javax.swing.JPasswordField txt_conf_senhaDialog;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emissor;
    private javax.swing.JTextField txt_end;
    private javax.swing.JTextField txt_espc_princ;
    private javax.swing.JTextField txt_espc_secund;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_num;
    private javax.swing.JTextField txt_num_conselho;
    private javax.swing.JFormattedTextField txt_rg;
    private javax.swing.JPasswordField txt_senhaDialog;
    private javax.swing.JFormattedTextField txt_tel_celular;
    private javax.swing.JFormattedTextField txt_tel_comerc;
    private javax.swing.JFormattedTextField txt_tel_resid;
    private javax.swing.JTextField txt_usuarioDialog;
    // End of variables declaration//GEN-END:variables
}
