/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PacienteCtrl;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Paciente;
import util.CPF;
import util.FormatarDatas;

/**
 *
 * @author leogo
 */
public class ListaPacienteView extends javax.swing.JInternalFrame {

    FormatarDatas datas = new FormatarDatas();
    ArrayList<Paciente> listaPaciente = new ArrayList<>();
    Paciente paciente = new Paciente();
    PacienteCtrl pacienteCtrl = new PacienteCtrl();

    /**
     * Creates new form ListaPacienteView
     */
    public ListaPacienteView() {
        initComponents();
        carregarPaciente();
        erroJlInvisible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_Paciente = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_nome1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cpf1 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_rg1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_data1 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jcb_sexo1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txt_peso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        jl_erro1 = new javax.swing.JLabel();
        jl_erro2 = new javax.swing.JLabel();
        jl_erro3 = new javax.swing.JLabel();
        jl_erro4 = new javax.swing.JLabel();
        jl_erro5 = new javax.swing.JLabel();
        jl_erro6 = new javax.swing.JLabel();
        jl_erro7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_end = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_cep = new javax.swing.JFormattedTextField();
        txt_numero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jcb_estado1 = new javax.swing.JComboBox<>();
        txt_tel_celular = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_cidade1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jl_erro8 = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        btn_fechar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_rg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcb_sexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcb_estado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btn_pesquisar = new javax.swing.JButton();
        txt_cidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_paciente = new javax.swing.JTable();
        btn_editar = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();

        jDialog_Paciente.setTitle("Editar Paciente");
        jDialog_Paciente.setBackground(new java.awt.Color(255, 255, 255));
        jDialog_Paciente.setBounds(new java.awt.Rectangle(300, 100, 754, 427));
        jDialog_Paciente.setPreferredSize(new java.awt.Dimension(754, 427));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Nome");

        txt_nome1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("CPF");

        try {
            txt_cpf1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("RG");

        txt_rg1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Data de Nascimento");

        try {
            txt_data1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_data1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Sexo");

        jcb_sexo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO - M", "FEMININO - F" }));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Peso kg");

        txt_peso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_peso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_pesoFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Altura ");

        txt_altura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_altura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_alturaFocusLost(evt);
            }
        });

        jl_erro1.setText("*");

        jl_erro2.setText("*");

        jl_erro3.setText("*");

        jl_erro4.setText("*");

        jl_erro5.setText("*");

        jl_erro6.setText("*");

        jl_erro7.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_erro4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(3, 3, 3)
                                .addComponent(jl_erro5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcb_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(2, 2, 2)
                                .addComponent(jl_erro6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_erro7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_altura)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(2, 2, 2)
                                .addComponent(jl_erro1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_erro2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_rg1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_erro3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jl_erro1)
                    .addComponent(jl_erro2)
                    .addComponent(jl_erro3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jl_erro4)
                    .addComponent(jl_erro5)
                    .addComponent(jl_erro6)
                    .addComponent(jl_erro7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_data1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço e Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Endereço");

        txt_end.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Bairro");

        txt_bairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("CEP");

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_numero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Número");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Estado");

        jcb_estado1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_estado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACRE - AC", "ALAGOAS - AL", "AMAPÁ - AP", "AMAZONAS - AM", "BAHIA  - BA", "CEARÁ - CE", "DISTRITO FEDERAL  - DF", "ESPÍRITO SANTO - ES", "GOIÁS - GO", "MARANHÃO - MA", "MATO GROSSO - MT", "MATO GROSSO DO SUL - MS", "MINAS GERAIS - MG", "PARÁ - PA", "PARAÍBA - PB", "PARANÁ - PR", "PERNAMBUCO - PE", "PIAUÍ - PI", "RIO DE JANEIRO - RJ", "RIO GRANDE DO NORTE - RN", "RIO GRANDE DO SUL - RS", "RONDÔNIA - RO", "RORAIMA - RR", "SANTA CATARINA - SC", "SÃO PAULO - SP", "SERGIPE - SE", "TOCANTINS - TO", " " }));

        try {
            txt_tel_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel_celular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Tel. Celular");

        txt_cidade1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel20.setText("Cidade");

        jl_erro8.setText("*");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(txt_end)
                    .addComponent(jLabel18)
                    .addComponent(jcb_estado1, 0, 174, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_cidade1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(txt_bairro)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_numero)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_erro8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jl_erro8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_estado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_24px.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_fechar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_fechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_fechar1.setText("Fechar");
        btn_fechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fechar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_fechar1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_fechar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_PacienteLayout = new javax.swing.GroupLayout(jDialog_Paciente.getContentPane());
        jDialog_Paciente.getContentPane().setLayout(jDialog_PacienteLayout);
        jDialog_PacienteLayout.setHorizontalGroup(
            jDialog_PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_PacienteLayout.setVerticalGroup(
            jDialog_PacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Pacientes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel1.setText("Nome");

        txt_nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setText("CPF");

        txt_rg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setText("RG");

        jcb_sexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "MASCULINO - M", "FEMININO - F" }));

        jLabel4.setText("Sexo");

        jcb_estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ACRE - AC", "ALAGOAS - AL", "AMAPÁ - AP", "AMAZONAS - AM", "BAHIA  - BA", "CEARÁ - CE", "DISTRITO FEDERAL  - DF", "ESPÍRITO SANTO - ES", "GOIÁS - GO", "MARANHÃO - MA", "MATO GROSSO - MT", "MATO GROSSO DO SUL - MS", "MINAS GERAIS - MG", "PARÁ - PA", "PARAÍBA - PB", "PARANÁ - PR", "PERNAMBUCO - PE", "PIAUÍ - PI", "RIO DE JANEIRO - RJ", "RIO GRANDE DO NORTE - RN", "RIO GRANDE DO SUL - RS", "RONDÔNIA - RO", "RORAIMA - RR", "SANTA CATARINA - SC", "SÃO PAULO - SP", "SERGIPE - SE", "TOCANTINS - TO", " " }));

        jLabel7.setText("Estado");

        btn_pesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search_24px.png"))); // NOI18N
        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        jLabel8.setText("Cidade");

        txt_cpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_nome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                        .addComponent(btn_pesquisar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_pesquisar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );

        jt_paciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jt_paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Nascimento", "Sexo", "Peso kg", "Altura cm", "Endereço", "Bairro", "CEP", "Cidade", "Estado", "Tel. Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_paciente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jt_paciente);
        if (jt_paciente.getColumnModel().getColumnCount() > 0) {
            jt_paciente.getColumnModel().getColumn(1).setMinWidth(150);
            jt_paciente.getColumnModel().getColumn(1).setPreferredWidth(250);
            jt_paciente.getColumnModel().getColumn(2).setMinWidth(90);
            jt_paciente.getColumnModel().getColumn(2).setPreferredWidth(100);
            jt_paciente.getColumnModel().getColumn(3).setMinWidth(80);
            jt_paciente.getColumnModel().getColumn(3).setPreferredWidth(90);
            jt_paciente.getColumnModel().getColumn(4).setMinWidth(90);
            jt_paciente.getColumnModel().getColumn(4).setPreferredWidth(100);
            jt_paciente.getColumnModel().getColumn(5).setMinWidth(90);
            jt_paciente.getColumnModel().getColumn(5).setPreferredWidth(100);
            jt_paciente.getColumnModel().getColumn(8).setMinWidth(150);
            jt_paciente.getColumnModel().getColumn(8).setPreferredWidth(200);
            jt_paciente.getColumnModel().getColumn(9).setMinWidth(150);
            jt_paciente.getColumnModel().getColumn(9).setPreferredWidth(200);
            jt_paciente.getColumnModel().getColumn(10).setMinWidth(90);
            jt_paciente.getColumnModel().getColumn(10).setPreferredWidth(100);
            jt_paciente.getColumnModel().getColumn(11).setMinWidth(100);
            jt_paciente.getColumnModel().getColumn(11).setPreferredWidth(150);
            jt_paciente.getColumnModel().getColumn(12).setMinWidth(120);
            jt_paciente.getColumnModel().getColumn(12).setPreferredWidth(160);
            jt_paciente.getColumnModel().getColumn(13).setMinWidth(90);
            jt_paciente.getColumnModel().getColumn(13).setPreferredWidth(100);
        }

        btn_editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit_24px.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_apagar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash Can_24px.png"))); // NOI18N
        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_fechar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_apagar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editar)
                    .addComponent(btn_apagar)
                    .addComponent(btn_fechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(260, 50, 868, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        listaPaciente = pacienteCtrl.retornarListaPacientePesquisa(txt_nome.getText().toUpperCase(), txt_cpf.getText(), txt_rg.getText(), jcb_sexo.getSelectedItem().toString(), jcb_estado.getSelectedItem().toString(), txt_cidade.getText().toUpperCase());

        DefaultTableModel modelo = (DefaultTableModel) jt_paciente.getModel();

        modelo.setNumRows(0);
        DecimalFormat d = new DecimalFormat("###,##0.000 kg");
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        int cont = listaPaciente.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaPaciente.get(i).getIdPaciente(),
                listaPaciente.get(i).getNome(),
                listaPaciente.get(i).getCpf(),
                listaPaciente.get(i).getRg(),
                formato.format(listaPaciente.get(i).getDataNascimento()),
                listaPaciente.get(i).getSexo(),
                d.format(listaPaciente.get(i).getPeso()),
                listaPaciente.get(i).getAltura(),
                listaPaciente.get(i).getEndereco(),
                listaPaciente.get(i).getBairro(),
                listaPaciente.get(i).getCep(),
                listaPaciente.get(i).getCidade(),
                listaPaciente.get(i).getEstadoUf(),
                listaPaciente.get(i).getTelCelular()
            });
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        int d = JOptionPane.showConfirmDialog(null, "Deseja apagar este registro?", "AVISO", JOptionPane.YES_NO_OPTION);
        if (d == 0) {
            try {
                if (jt_paciente.getSelectedRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Selecione um registro", "AVISO", JOptionPane.ERROR_MESSAGE);
                } else {
                    int[] rows = jt_paciente.getSelectedRows();
                    for (int i = 0; i < rows.length; i++) {
                        int codigo = (int) jt_paciente.getValueAt(rows[i], 0);
                        pacienteCtrl.deletPacienteCtrl(codigo);
                    }
                    JOptionPane.showMessageDialog(null, "Resgistro apagado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
        carregarPaciente();
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void txt_pesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pesoFocusLost
        try {
            String sv = txt_peso.getText();
            String vsf = sv.replace(" ", "").replace(".", "").replace(",", ".");
            Double valor = new Double(vsf);
            txt_peso.setText(String.valueOf(valor));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_pesoFocusLost

    private void txt_alturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alturaFocusLost
        try {
            String sv = txt_altura.getText();
            String vsf = sv.replace(" ", "").replace(".", "").replace(",", ".");
            Double valor = new Double(vsf);
            txt_altura.setText(String.valueOf(valor));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_alturaFocusLost

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int linhaSelecionada = this.jt_paciente.getSelectedRow();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            int codigo = (int) jt_paciente.getValueAt(linhaSelecionada, 0);

            //recuperar dados do banco
            paciente = pacienteCtrl.retoPacienteIdCtrl(codigo);

            //setar na interface
            txt_nome1.setText(paciente.getNome().toUpperCase());
            txt_cpf1.setText(paciente.getCpf().replaceAll("[.-]", ""));
            txt_rg1.setText(paciente.getRg());
            jcb_sexo1.setSelectedItem(paciente.getSexo());
            txt_data1.setText(formato.format(paciente.getDataNascimento()));
            txt_peso.setText(String.valueOf(paciente.getPeso()));
            txt_altura.setText(String.valueOf(paciente.getAltura()));
            txt_end.setText(paciente.getEndereco());
            txt_bairro.setText(paciente.getBairro());
            txt_cep.setText(paciente.getCep());
            txt_numero.setText(paciente.getNumero());
            jcb_estado1.setSelectedItem(paciente.getEstadoUf());
            txt_cidade1.setText(paciente.getCidade());
            txt_tel_celular.setText(paciente.getTelCelular());

            jDialog_Paciente.setModal(true);
            jDialog_Paciente.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione uma registro", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_fechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fechar1ActionPerformed
        jDialog_Paciente.dispose();
    }//GEN-LAST:event_btn_fechar1ActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        CPF pf = new CPF(txt_cpf1.getText());
        if (pf.isCPF() || pf.equals("   .   .   -  ")) {
            if (txt_nome1.getText().trim().equals("") || txt_cpf1.getText().equals("") || txt_rg1.getText().trim().equals("") || jcb_sexo1.getSelectedItem().equals("") || txt_data1.getText().equals("  /  /    ") || txt_tel_celular.getText().equals("") || txt_peso.getText().trim().equals("") || txt_altura.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                erroJlVisible();
                resetErroBorderLine();
            } else {
                alterarPaciente();
                jDialog_Paciente.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void carregarPaciente() {
        listaPaciente = pacienteCtrl.retoListPacienteCrtl();
        DefaultTableModel modelo = (DefaultTableModel) jt_paciente.getModel();
        modelo.setRowCount(0);

        //DecimalFormat df = new DecimalFormat("##,##0.000");
        DecimalFormat d = new DecimalFormat("###,##0.000 kg");
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
        int cont = listaPaciente.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaPaciente.get(i).getIdPaciente(),
                listaPaciente.get(i).getNome(),
                listaPaciente.get(i).getCpf(),
                listaPaciente.get(i).getRg(),
                formato.format(listaPaciente.get(i).getDataNascimento()),
                listaPaciente.get(i).getSexo(),
                d.format(listaPaciente.get(i).getPeso()),
                listaPaciente.get(i).getAltura(),
                listaPaciente.get(i).getEndereco(),
                listaPaciente.get(i).getBairro(),
                listaPaciente.get(i).getCep(),
                listaPaciente.get(i).getCidade(),
                listaPaciente.get(i).getEstadoUf(),
                listaPaciente.get(i).getTelCelular()
            });
        }
    }

    private void alterarPaciente() {
        paciente.setNome(txt_nome1.getText().toUpperCase());
        paciente.setCpf(txt_cpf1.getText().replaceAll("[.-]", ""));
        paciente.setRg(txt_rg1.getText());
        try {
            paciente.setDataNascimento(datas.converterDataStringParaDate(txt_data1.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
        paciente.setSexo(jcb_sexo1.getSelectedItem().toString());
        paciente.setPeso(Double.parseDouble(txt_peso.getText()));
        paciente.setAltura(Double.parseDouble(txt_altura.getText()));
        paciente.setEndereco(txt_end.getText());
        paciente.setBairro(txt_bairro.getText());
        paciente.setCep(txt_cep.getText());
        paciente.setNumero(txt_numero.getText());
        paciente.setEstadoUf(jcb_estado1.getSelectedItem().toString());
        paciente.setCidade(txt_cidade1.getText());
        paciente.setTelCelular(txt_tel_celular.getText());

        if (pacienteCtrl.upPacienteCtrl(paciente)) {
            JOptionPane.showMessageDialog(null, "Alterado com Sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            this.carregarPaciente();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao Tentar Alterar", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void erroJlInvisible() {
        jl_erro1.setVisible(false);
        jl_erro2.setVisible(false);
        jl_erro3.setVisible(false);
        jl_erro4.setVisible(false);
        jl_erro5.setVisible(false);
        jl_erro6.setVisible(false);
        jl_erro7.setVisible(false);
        jl_erro8.setVisible(false);
    }

    private void erroJlVisible() {
        jl_erro1.setVisible(true);
        jl_erro2.setVisible(true);
        jl_erro3.setVisible(true);
        jl_erro4.setVisible(true);
        jl_erro5.setVisible(true);
        jl_erro6.setVisible(true);
        jl_erro7.setVisible(true);
        jl_erro8.setVisible(true);

    }

    private void resetErroBorderLine() {
        jl_erro1.setForeground(Color.red);
        jl_erro2.setForeground(Color.red);
        jl_erro3.setForeground(Color.red);
        jl_erro4.setForeground(Color.red);
        jl_erro5.setForeground(Color.red);
        jl_erro6.setForeground(Color.red);
        jl_erro7.setForeground(Color.red);
        jl_erro8.setForeground(Color.red);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_fechar1;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JDialog jDialog_Paciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_estado;
    private javax.swing.JComboBox<String> jcb_estado1;
    private javax.swing.JComboBox<String> jcb_sexo;
    private javax.swing.JComboBox<String> jcb_sexo1;
    private javax.swing.JLabel jl_erro1;
    private javax.swing.JLabel jl_erro2;
    private javax.swing.JLabel jl_erro3;
    private javax.swing.JLabel jl_erro4;
    private javax.swing.JLabel jl_erro5;
    private javax.swing.JLabel jl_erro6;
    private javax.swing.JLabel jl_erro7;
    private javax.swing.JLabel jl_erro8;
    private javax.swing.JTable jt_paciente;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JFormattedTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_cidade1;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JFormattedTextField txt_cpf1;
    private javax.swing.JFormattedTextField txt_data1;
    private javax.swing.JTextField txt_end;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_nome1;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_rg;
    private javax.swing.JTextField txt_rg1;
    private javax.swing.JFormattedTextField txt_tel_celular;
    // End of variables declaration//GEN-END:variables
}
