/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MedicoCtrl;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Medico;
import util.CPF;
import util.FormatarDatas;

/**
 *
 * @author leogo
 */
public class ListaMedicoView extends javax.swing.JInternalFrame {

    ArrayList<Medico> listaMedico = new ArrayList<>();
    MedicoCtrl medicoCtrl = new MedicoCtrl();
    Medico medico = new Medico();
    CadastroMedicoView cadMedico;
    FormatarDatas datas = new FormatarDatas();

    /**
     * Creates new form ListaMedicoView
     */
    public ListaMedicoView() {
        initComponents();
        carregarMedico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_Alterar = new javax.swing.JDialog();
        jPanelFormMedico = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        jcb_sexo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_data = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jcb_civil = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_rg = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_emissor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_end = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_bairro = new javax.swing.JTextField();
        txt_cep = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        jcb_estado = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txt_tel_resid = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_tel_celular = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jl_Error = new javax.swing.JLabel();
        jl_Error1 = new javax.swing.JLabel();
        jl_Error2 = new javax.swing.JLabel();
        jl_Error3 = new javax.swing.JLabel();
        jl_Error4 = new javax.swing.JLabel();
        jl_Error5 = new javax.swing.JLabel();
        jl_Error6 = new javax.swing.JLabel();
        jl_Error7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txt_num_conselho = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_espc_princ = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_atuacao = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_espc_secund = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_tel_comerc = new javax.swing.JFormattedTextField();
        jl_Error8 = new javax.swing.JLabel();
        jl_Error9 = new javax.swing.JLabel();
        jl_Error10 = new javax.swing.JLabel();
        btn_cancelar1 = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_pesq_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_pesq_nConselho = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_pesq_rg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_pesq_cidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_pesq_funcao = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        txt_pesq_cpf = new javax.swing.JFormattedTextField();
        txt_pesq_estado = new javax.swing.JComboBox<>();
        txt_pesq_especialidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_medico = new javax.swing.JTable();

        jDialog_Alterar.setTitle("Editar Cadastro");
        jDialog_Alterar.setBackground(new java.awt.Color(255, 255, 255));
        jDialog_Alterar.setBounds(new java.awt.Rectangle(300, 50, 732, 560));
        jDialog_Alterar.setType(java.awt.Window.Type.POPUP);

        jPanelFormMedico.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessois", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        txt_nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nomeFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Nome Completo");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("CPF");

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cpfFocusGained(evt);
            }
        });

        jcb_sexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO - M", "FEMININO - F" }));
        jcb_sexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcb_sexoFocusGained(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Sexo");

        try {
            txt_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dataFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Data de Nascimento");

        jcb_civil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_civil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTEIRO(A)", "CASADO(A)", "VIÚVO(A)", "DIVORCIADO(A)", " " }));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Estado Civil");

        jLabel14.setText("RG");

        txt_rg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rgFocusGained(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Órgão Emissor");

        txt_emissor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel16.setText("Endereço");

        jLabel17.setText("Número");

        jLabel18.setText("Bairro");

        try {
            txt_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("CEP");

        jLabel20.setText("Cidade");

        jcb_estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACRE - AC", "ALAGOAS - AL", "AMAPÁ - AP", "AMAZONAS - AM", "BAHIA  - BA", "CEARÁ - CE", "DISTRITO FEDERAL  - DF", "ESPÍRITO SANTO - ES", "GOIÁS - GO", "MARANHÃO - MA", "MATO GROSSO - MT", "MATO GROSSO DO SUL - MS", "MINAS GERAIS - MG", "PARÁ - PA", "PARAÍBA - PB", "PARANÁ - PR", "PERNAMBUCO - PE", "PIAUÍ - PI", "RIO DE JANEIRO - RJ", "RIO GRANDE DO NORTE - RN", "RIO GRANDE DO SUL - RS", "RONDÔNIA - RO", "RORAIMA - RR", "SANTA CATARINA - SC", "SÃO PAULO - SP", "SERGIPE - SE", "TOCANTINS - TO" }));

        jLabel21.setText("Estado UF");

        try {
            txt_tel_resid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel_resid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_tel_resid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_tel_residFocusGained(evt);
            }
        });

        jLabel22.setText("Telefone Residencial");

        try {
            txt_tel_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel_celular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_tel_celular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_tel_celularFocusGained(evt);
            }
        });

        jLabel23.setText("Telefone Celular");

        jl_Error.setText("*");

        jl_Error1.setText("*");

        jl_Error2.setText("*");

        jl_Error3.setText("*");

        jl_Error4.setText("*");

        jl_Error5.setText("*");

        jl_Error6.setText("*");

        jl_Error7.setText("*");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_cidade))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_Error4))
                            .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_Error5)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jcb_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_end)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel18)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel19)
                                .addGap(151, 151, 151)
                                .addComponent(jLabel20))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error))
                                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error1)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error2)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error3))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(txt_emissor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tel_resid, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error6)))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_Error7))
                                    .addComponent(txt_tel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jl_Error))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jl_Error1))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jl_Error2))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jl_Error3)))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jl_Error4))
                            .addGap(5, 5, 5)
                            .addComponent(jcb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jl_Error5))
                            .addGap(5, 5, 5)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(5, 5, 5)
                            .addComponent(jcb_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(txt_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jl_Error6))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jl_Error7)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel_resid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Profissionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Número do Conselho");

        txt_num_conselho.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_num_conselho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_num_conselhoFocusGained(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Especialidade Principal");

        txt_espc_princ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_espc_princ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_espc_princFocusGained(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Email Comercial");

        txt_email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Área de Atuação");

        txt_atuacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_atuacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_atuacaoFocusGained(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Especialidade Secudária (opcional)");

        txt_espc_secund.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Telefone Comercial (opcional)");

        try {
            txt_tel_comerc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel_comerc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jl_Error8.setText("*");

        jl_Error9.setText("*");

        jl_Error10.setText("*");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_atuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(3, 3, 3)
                                .addComponent(jl_Error10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_tel_comerc)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_num_conselho, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(4, 4, 4)
                                .addComponent(jl_Error8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(5, 5, 5)
                                .addComponent(jl_Error9))
                            .addComponent(txt_espc_princ, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_espc_secund))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(jl_Error8)
                    .addComponent(jl_Error9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_num_conselho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_espc_princ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_espc_secund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29)
                    .addComponent(jl_Error10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_atuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel_comerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_cancelar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_cancelar1.setText("Fechar");
        btn_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar1ActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_24px.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormMedicoLayout = new javax.swing.GroupLayout(jPanelFormMedico);
        jPanelFormMedico.setLayout(jPanelFormMedicoLayout);
        jPanelFormMedicoLayout.setHorizontalGroup(
            jPanelFormMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormMedicoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cancelar1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar)))
                .addContainerGap())
        );
        jPanelFormMedicoLayout.setVerticalGroup(
            jPanelFormMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanelFormMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar1)
                    .addComponent(btn_salvar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog_AlterarLayout = new javax.swing.GroupLayout(jDialog_Alterar.getContentPane());
        jDialog_Alterar.getContentPane().setLayout(jDialog_AlterarLayout);
        jDialog_AlterarLayout.setHorizontalGroup(
            jDialog_AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFormMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_AlterarLayout.setVerticalGroup(
            jDialog_AlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFormMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Médicos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nome");

        txt_pesq_nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("CPF");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nº Conselho");

        txt_pesq_nConselho.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("RG");

        txt_pesq_rg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Estado");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Cidade");

        txt_pesq_cidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel7.setText("Função");

        btn_pesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search_24px.png"))); // NOI18N
        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        txt_pesq_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txt_pesq_cpf.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        txt_pesq_cpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txt_pesq_estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_pesq_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Acre - AC", "Alagoas - AL", "Amapá - AP", "Amazonas - AM", "Bahia  - BA", "Ceará - CE", "Distrito Federal  - DF", "Espírito Santo - ES", "Goiás - GO", "Maranhão - MA", "Mato Grosso - MT", "Mato Grosso do Sul - MS", "Minas Gerais - MG", "Pará - PA", "Paraíba - PB", "Paraná - PR", "Pernambuco - PE", "Piauí - PI", "Rio de Janeiro - RJ", "Rio Grande do Norte - RN", "Rio Grande do Sul - RS", "Rondônia - RO", "Roraima - RR", "Santa Catarina - SC", "São Paulo - SP", "Sergipe - SE", "Tocantins - TO" }));

        jLabel8.setText("Especidalidade");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pesq_nConselho, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addComponent(txt_pesq_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(btn_pesquisar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(txt_pesq_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pesq_cpf)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pesq_rg))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pesq_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pesq_funcao))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_pesq_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(txt_pesq_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(txt_pesq_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_pesq_funcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_pesq_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(txt_pesq_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_pesq_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pesq_nConselho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txt_pesq_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_pesquisar)))
        );

        btn_editar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Edit_24px.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_apagar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash Can_24px.png"))); // NOI18N
        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_cancelar.setText("Fechar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jt_medico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jt_medico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Orgão Emissor", "Sexo", "Nascimento", "Nº Conselho", "Estado Civil", "Função", "Espc. Principal", "Espc. Secundaria", "Endereço", "Bairro", "Número", "CEP", "Cidade", "Estado", "Tel. Residência", "Tel. Celular", "Tel Comercial", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_medico.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jt_medico.setGridColor(new java.awt.Color(0, 0, 0));
        jt_medico.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jScrollPane1.setViewportView(jt_medico);
        if (jt_medico.getColumnModel().getColumnCount() > 0) {
            jt_medico.getColumnModel().getColumn(1).setMinWidth(150);
            jt_medico.getColumnModel().getColumn(1).setPreferredWidth(200);
            jt_medico.getColumnModel().getColumn(1).setMaxWidth(200);
            jt_medico.getColumnModel().getColumn(2).setMinWidth(90);
            jt_medico.getColumnModel().getColumn(2).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(2).setMaxWidth(110);
            jt_medico.getColumnModel().getColumn(3).setMinWidth(80);
            jt_medico.getColumnModel().getColumn(3).setPreferredWidth(90);
            jt_medico.getColumnModel().getColumn(3).setMaxWidth(100);
            jt_medico.getColumnModel().getColumn(4).setMinWidth(100);
            jt_medico.getColumnModel().getColumn(4).setPreferredWidth(120);
            jt_medico.getColumnModel().getColumn(4).setMaxWidth(150);
            jt_medico.getColumnModel().getColumn(5).setMinWidth(90);
            jt_medico.getColumnModel().getColumn(5).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(5).setMaxWidth(110);
            jt_medico.getColumnModel().getColumn(6).setMinWidth(90);
            jt_medico.getColumnModel().getColumn(6).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(6).setMaxWidth(110);
            jt_medico.getColumnModel().getColumn(7).setMinWidth(90);
            jt_medico.getColumnModel().getColumn(7).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(7).setMaxWidth(110);
            jt_medico.getColumnModel().getColumn(8).setMinWidth(90);
            jt_medico.getColumnModel().getColumn(8).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(8).setMaxWidth(120);
            jt_medico.getColumnModel().getColumn(9).setMinWidth(100);
            jt_medico.getColumnModel().getColumn(9).setPreferredWidth(150);
            jt_medico.getColumnModel().getColumn(9).setMaxWidth(170);
            jt_medico.getColumnModel().getColumn(10).setMinWidth(100);
            jt_medico.getColumnModel().getColumn(10).setPreferredWidth(150);
            jt_medico.getColumnModel().getColumn(10).setMaxWidth(170);
            jt_medico.getColumnModel().getColumn(11).setMinWidth(100);
            jt_medico.getColumnModel().getColumn(11).setPreferredWidth(150);
            jt_medico.getColumnModel().getColumn(11).setMaxWidth(170);
            jt_medico.getColumnModel().getColumn(12).setMinWidth(150);
            jt_medico.getColumnModel().getColumn(12).setPreferredWidth(150);
            jt_medico.getColumnModel().getColumn(12).setMaxWidth(200);
            jt_medico.getColumnModel().getColumn(13).setMinWidth(130);
            jt_medico.getColumnModel().getColumn(13).setPreferredWidth(150);
            jt_medico.getColumnModel().getColumn(13).setMaxWidth(170);
            jt_medico.getColumnModel().getColumn(14).setMinWidth(50);
            jt_medico.getColumnModel().getColumn(14).setPreferredWidth(70);
            jt_medico.getColumnModel().getColumn(14).setMaxWidth(80);
            jt_medico.getColumnModel().getColumn(15).setMinWidth(90);
            jt_medico.getColumnModel().getColumn(15).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(15).setMaxWidth(110);
            jt_medico.getColumnModel().getColumn(16).setMinWidth(130);
            jt_medico.getColumnModel().getColumn(16).setPreferredWidth(150);
            jt_medico.getColumnModel().getColumn(16).setMaxWidth(180);
            jt_medico.getColumnModel().getColumn(17).setMinWidth(130);
            jt_medico.getColumnModel().getColumn(17).setPreferredWidth(150);
            jt_medico.getColumnModel().getColumn(17).setMaxWidth(190);
            jt_medico.getColumnModel().getColumn(18).setMinWidth(100);
            jt_medico.getColumnModel().getColumn(18).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(18).setMaxWidth(100);
            jt_medico.getColumnModel().getColumn(19).setMinWidth(100);
            jt_medico.getColumnModel().getColumn(19).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(19).setMaxWidth(100);
            jt_medico.getColumnModel().getColumn(20).setMinWidth(100);
            jt_medico.getColumnModel().getColumn(20).setPreferredWidth(100);
            jt_medico.getColumnModel().getColumn(20).setMaxWidth(100);
            jt_medico.getColumnModel().getColumn(21).setMinWidth(100);
            jt_medico.getColumnModel().getColumn(21).setPreferredWidth(150);
            jt_medico.getColumnModel().getColumn(21).setMaxWidth(180);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_apagar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editar)
                    .addComponent(btn_apagar)
                    .addComponent(btn_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(160, 20, 1055, 632);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        listaMedico = medicoCtrl.retornarListaMedicoPesquisaCtrl(txt_pesq_nome.getText().toUpperCase(), txt_pesq_rg.getText(),
                txt_pesq_cpf.getText(), txt_pesq_nConselho.getText(), txt_pesq_estado.getSelectedItem().toString().toUpperCase(),
                txt_pesq_cidade.getText().toUpperCase(), txt_pesq_funcao.getText().toUpperCase(), txt_pesq_especialidade.getText().toUpperCase());
        
        DefaultTableModel medicoNome = (DefaultTableModel) jt_medico.getModel();

        medicoNome.setNumRows(0);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        int cont = listaMedico.size();
        for (int i = 0; i < cont; i++) {
            medicoNome.addRow(new Object[]{
                listaMedico.get(i).getIdMedico(),
                listaMedico.get(i).getNome(),
                listaMedico.get(i).getCpf(),
                listaMedico.get(i).getRg(),
                listaMedico.get(i).getOrgaoEmissor(),
                listaMedico.get(i).getSexo(),
                formato.format(listaMedico.get(i).getDataNasc()),
                listaMedico.get(i).getCrm(),
                listaMedico.get(i).getEstadoCivil(),
                listaMedico.get(i).getFuncao(),
                listaMedico.get(i).getEspcPrincipal(),
                listaMedico.get(i).getEspcSecundaria(),
                listaMedico.get(i).getEndereco(),
                listaMedico.get(i).getBairro(),
                listaMedico.get(i).getNumero(),
                listaMedico.get(i).getCep(),
                listaMedico.get(i).getCidade(),
                listaMedico.get(i).getEstado(),
                listaMedico.get(i).getTelrrsid(),
                listaMedico.get(i).getTelCelular(),
                listaMedico.get(i).getTelComerc(),
                listaMedico.get(i).getEmailComerc()
            });
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int linhaSelecionada = this.jt_medico.getSelectedRow();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            int codigo = (int) jt_medico.getValueAt(linhaSelecionada, 0);

            //recuperar dados do banco
            medico = medicoCtrl.retoMedicoIdCtrl(codigo);

            //setar na interface
            txt_nome.setText(medico.getNome().toUpperCase());
            txt_cpf.setText(medico.getCpf());
            txt_rg.setText(medico.getRg());
            txt_emissor.setText(medico.getOrgaoEmissor().toUpperCase());
            jcb_sexo.setSelectedItem(medico.getSexo());
            txt_data.setText(formato.format(medico.getDataNasc()));
            jcb_civil.setSelectedItem(medico.getEstadoCivil());
            txt_end.setText(medico.getEndereco());
            txt_num.setText(medico.getNumero());
            txt_bairro.setText(medico.getBairro());
            txt_cep.setText(medico.getCep());
            txt_cidade.setText(medico.getCidade());
            jcb_estado.setSelectedItem(medico.getEstado());
            txt_tel_resid.setText(medico.getTelrrsid());
            txt_tel_celular.setText(medico.getTelCelular());
            txt_num_conselho.setText(medico.getCrm().toUpperCase());
            txt_espc_princ.setText(medico.getEspcPrincipal());
            txt_espc_secund.setText(medico.getEspcSecundaria());
            txt_email.setText(medico.getEmailComerc());
            txt_atuacao.setText(medico.getFuncao());
            txt_tel_comerc.setText(medico.getTelComerc());

            jDialog_Alterar.setModal(true);
            jDialog_Alterar.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione uma registro", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nomeFocusGained
        erroJlInvisible();
    }//GEN-LAST:event_txt_nomeFocusGained

    private void txt_cpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusGained
        erroJlInvisible();
    }//GEN-LAST:event_txt_cpfFocusGained

    private void jcb_sexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_sexoFocusGained
        erroJlInvisible();
    }//GEN-LAST:event_jcb_sexoFocusGained

    private void txt_dataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dataFocusGained
        erroJlInvisible();
    }//GEN-LAST:event_txt_dataFocusGained

    private void txt_rgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rgFocusGained
        resetErroBorderLine();
    }//GEN-LAST:event_txt_rgFocusGained

    private void txt_tel_residFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tel_residFocusGained
        resetErroBorderLine();
    }//GEN-LAST:event_txt_tel_residFocusGained

    private void txt_tel_celularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tel_celularFocusGained
        erroJlInvisible();
    }//GEN-LAST:event_txt_tel_celularFocusGained

    private void txt_num_conselhoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_num_conselhoFocusGained
        erroJlInvisible();
    }//GEN-LAST:event_txt_num_conselhoFocusGained

    private void txt_espc_princFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_espc_princFocusGained
        erroJlInvisible();
    }//GEN-LAST:event_txt_espc_princFocusGained

    private void txt_atuacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_atuacaoFocusGained
        erroJlInvisible();
    }//GEN-LAST:event_txt_atuacaoFocusGained

    private void btn_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar1ActionPerformed
        jDialog_Alterar.dispose();
    }//GEN-LAST:event_btn_cancelar1ActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        CPF pf = new CPF(txt_cpf.getText());
        if (pf.isCPF() || pf.equals("   .   .   -  ")) {
            if (txt_nome.getText().equals("") || txt_cpf.getText().equals("") || txt_rg.getText().equals("") || jcb_sexo.getSelectedItem().equals("") || txt_data.getText().equals("  /  /    ") || txt_tel_resid.getText().equals("") || txt_tel_celular.getText().equals("") || txt_num_conselho.getText().equals("") || txt_espc_princ.getText().equals("") || txt_atuacao.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                erroJlVisible();
                resetErroBorderLine();
            } else {
                alterarMedico();
                jDialog_Alterar.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        int d = JOptionPane.showConfirmDialog(null, "Deseja apagar este registro?", "AVISO", JOptionPane.YES_NO_OPTION);
        if (d == 0) {
            try {
                if (jt_medico.getSelectedRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Selecione um registro", "AVISO", JOptionPane.ERROR_MESSAGE);
                } else {
                    int[] rows = jt_medico.getSelectedRows();
                    for (int i = 0; i < rows.length; i++) {
                        int codigo = (int) jt_medico.getValueAt(rows[i], 0);
                        medicoCtrl.deletMedicoCtrl(codigo);
                    }
                    JOptionPane.showMessageDialog(null, "Resgistro apagado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
        carregarMedico();
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void alterarMedico() {
        medico.setNome(txt_nome.getText().toUpperCase());
        medico.setCpf(txt_cpf.getText().replaceAll("[.-]", ""));
        medico.setRg(txt_rg.getText());
        medico.setOrgaoEmissor(txt_emissor.getText().toUpperCase());
        medico.setCrm(txt_num_conselho.getText().toUpperCase());
        medico.setSexo(jcb_sexo.getSelectedItem().toString());
        try {
            medico.setDataNasc(datas.converterDataStringParaDate(txt_data.getText()));
        } catch (Exception e) {
            e.printStackTrace();
        }
        medico.setEstadoCivil(jcb_civil.getSelectedItem().toString());
        medico.setEndereco(txt_end.getText().toUpperCase());
        medico.setNumero(txt_num.getText());
        medico.setBairro(txt_bairro.getText().toUpperCase());
        medico.setCep(txt_cep.getText());
        medico.setCidade(txt_cidade.getText().toUpperCase());
        medico.setEstado(jcb_estado.getSelectedItem().toString());
        medico.setTelrrsid(txt_tel_resid.getText());
        medico.setTelCelular(txt_tel_celular.getText());
        medico.setEspcPrincipal(txt_espc_princ.getText().toUpperCase());
        medico.setEspcSecundaria(txt_espc_secund.getText().toUpperCase());
        medico.setEmailComerc(txt_email.getText().toUpperCase());
        medico.setFuncao(txt_atuacao.getText().toUpperCase());
        medico.setTelComerc(txt_tel_comerc.getText());

        if (medicoCtrl.upMedicoCtrl(medico)) {
            JOptionPane.showMessageDialog(null, "Alterado com Sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            this.carregarMedico();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao Tentar Alterar", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void erroJlVisible() {
        jl_Error.setVisible(true);
        jl_Error1.setVisible(true);
        jl_Error2.setVisible(true);
        jl_Error3.setVisible(true);
        jl_Error4.setVisible(true);
        jl_Error5.setVisible(true);
        jl_Error6.setVisible(true);
        jl_Error7.setVisible(true);
        jl_Error8.setVisible(true);
        jl_Error9.setVisible(true);
        jl_Error10.setVisible(false);
    }

    private void erroJlInvisible() {
        jl_Error.setVisible(false);
        jl_Error1.setVisible(false);
        jl_Error2.setVisible(false);
        jl_Error3.setVisible(false);
        jl_Error4.setVisible(false);
        jl_Error5.setVisible(false);
        jl_Error6.setVisible(false);
        jl_Error7.setVisible(false);
        jl_Error8.setVisible(false);
        jl_Error9.setVisible(false);
        jl_Error10.setVisible(false);
    }

    private void resetErroBorderLine() {
        jl_Error.setForeground(Color.red);
        jl_Error1.setForeground(Color.red);
        jl_Error2.setForeground(Color.red);
        jl_Error3.setForeground(Color.red);
        jl_Error4.setForeground(Color.red);
        jl_Error5.setForeground(Color.red);
        jl_Error6.setForeground(Color.red);
        jl_Error7.setForeground(Color.red);
        jl_Error8.setForeground(Color.red);
        jl_Error9.setForeground(Color.red);
        jl_Error10.setForeground(Color.red);
    }

    private void carregarMedico() {
        listaMedico = medicoCtrl.retoListMedicoCrtl();
        DefaultTableModel modelo = (DefaultTableModel) jt_medico.getModel();
        modelo.setNumRows(0);

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        int cont = listaMedico.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaMedico.get(i).getIdMedico(),
                listaMedico.get(i).getNome(),
                listaMedico.get(i).getCpf(),
                listaMedico.get(i).getRg(),
                listaMedico.get(i).getOrgaoEmissor(),
                listaMedico.get(i).getSexo(),
                formato.format(listaMedico.get(i).getDataNasc()),
                listaMedico.get(i).getCrm(),
                listaMedico.get(i).getEstadoCivil(),
                listaMedico.get(i).getFuncao(),
                listaMedico.get(i).getEspcPrincipal(),
                listaMedico.get(i).getEspcSecundaria(),
                listaMedico.get(i).getEndereco(),
                listaMedico.get(i).getBairro(),
                listaMedico.get(i).getNumero(),
                listaMedico.get(i).getCep(),
                listaMedico.get(i).getCidade(),
                listaMedico.get(i).getEstado(),
                listaMedico.get(i).getTelrrsid(),
                listaMedico.get(i).getTelCelular(),
                listaMedico.get(i).getTelComerc(),
                listaMedico.get(i).getEmailComerc()

            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelar1;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JDialog jDialog_Alterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelFormMedico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_civil;
    private javax.swing.JComboBox<String> jcb_estado;
    private javax.swing.JComboBox<String> jcb_sexo;
    private javax.swing.JLabel jl_Error;
    private javax.swing.JLabel jl_Error1;
    private javax.swing.JLabel jl_Error10;
    private javax.swing.JLabel jl_Error2;
    private javax.swing.JLabel jl_Error3;
    private javax.swing.JLabel jl_Error4;
    private javax.swing.JLabel jl_Error5;
    private javax.swing.JLabel jl_Error6;
    private javax.swing.JLabel jl_Error7;
    private javax.swing.JLabel jl_Error8;
    private javax.swing.JLabel jl_Error9;
    private javax.swing.JTable jt_medico;
    private javax.swing.JTextField txt_atuacao;
    private javax.swing.JTextField txt_bairro;
    private javax.swing.JFormattedTextField txt_cep;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emissor;
    private javax.swing.JTextField txt_end;
    private javax.swing.JTextField txt_espc_princ;
    private javax.swing.JTextField txt_espc_secund;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_num;
    private javax.swing.JTextField txt_num_conselho;
    private javax.swing.JTextField txt_pesq_cidade;
    private javax.swing.JFormattedTextField txt_pesq_cpf;
    private javax.swing.JTextField txt_pesq_especialidade;
    private javax.swing.JComboBox<String> txt_pesq_estado;
    private javax.swing.JTextField txt_pesq_funcao;
    private javax.swing.JTextField txt_pesq_nConselho;
    private javax.swing.JTextField txt_pesq_nome;
    private javax.swing.JTextField txt_pesq_rg;
    private javax.swing.JFormattedTextField txt_rg;
    private javax.swing.JFormattedTextField txt_tel_celular;
    private javax.swing.JFormattedTextField txt_tel_comerc;
    private javax.swing.JFormattedTextField txt_tel_resid;
    // End of variables declaration//GEN-END:variables
}
