/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AgendaCtrl;
import controller.GenericCtrl;
import controller.MedicoCtrl;
import controller.PacienteCtrl;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Agenda;
import model.Generic;
import model.Medico;
import model.Paciente;

/**
 *
 * @author leogo
 */
public class ListaAgendaView extends javax.swing.JInternalFrame {

    Paciente paciente = new Paciente();
    PacienteCtrl pacienteCtrl = new PacienteCtrl();
    ArrayList<Paciente> listarPaciente = new ArrayList<>();

    Medico medico = new Medico();
    MedicoCtrl medicoCtrl = new MedicoCtrl();
    ArrayList<Medico> listarMedico = new ArrayList<>();

    Agenda agenda = new Agenda();
    AgendaCtrl agendaCtrl = new AgendaCtrl();
    ArrayList<Agenda> listaAgenda = new ArrayList<>();
    ArrayList<Generic> listaAgendaMedPac = new ArrayList<>();
    GenericCtrl genericCtrl = new GenericCtrl();

    /**
     * Creates new form ListaAgendaView
     */
    public ListaAgendaView() {
        initComponents();
        carregarAgenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcb_realizada = new javax.swing.JComboBox<>();
        btn_pesquisar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_agenda = new javax.swing.JTable();
        btn_fechar = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Agenda de Consultas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(698, 559));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Consultas Realizadas?");

        jcb_realizada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_realizada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "SIM", "NÃO" }));

        btn_pesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search_24px.png"))); // NOI18N
        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jLabel5.setText("Consultas Realizadas");

        jLabel6.setText("Consultas não Realizadas");

        jLabel7.setText("Consultas com Data Vencida");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcb_realizada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_realizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pesquisar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jt_agenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jt_agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Paciente", "Médico", "Data", "Horário", "Descrição", "Consulta Realizada?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_agenda.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jt_agenda);
        if (jt_agenda.getColumnModel().getColumnCount() > 0) {
            jt_agenda.getColumnModel().getColumn(1).setMinWidth(150);
            jt_agenda.getColumnModel().getColumn(2).setPreferredWidth(200);
            jt_agenda.getColumnModel().getColumn(3).setMinWidth(100);
            jt_agenda.getColumnModel().getColumn(3).setPreferredWidth(120);
            jt_agenda.getColumnModel().getColumn(4).setMinWidth(80);
            jt_agenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            jt_agenda.getColumnModel().getColumn(5).setMinWidth(200);
            jt_agenda.getColumnModel().getColumn(5).setPreferredWidth(250);
            jt_agenda.getColumnModel().getColumn(6).setMinWidth(110);
            jt_agenda.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        btn_fechar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_24px.png"))); // NOI18N
        btn_fechar.setText("Fechar");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        btn_deletar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash Can_24px.png"))); // NOI18N
        btn_deletar.setText("Apagar");
        btn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_fechar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_deletar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fechar)
                    .addComponent(btn_deletar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(300, 100, 746, 484);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        if (jcb_realizada.getSelectedItem().toString().equals("SELECIONE")) {
            limparTable();
            carregarAgenda();
        } else {
            listaAgendaMedPac = genericCtrl.retornarListaAgendaPesquisa(jcb_realizada.getSelectedItem().toString());
            DefaultTableModel modelo = (DefaultTableModel) jt_agenda.getModel();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            modelo.setNumRows(0);
            int cont = listaAgendaMedPac.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaAgendaMedPac.get(i).getAgenda().getId_agenda(),
                    listaAgendaMedPac.get(i).getPaciente().getNome(),
                    listaAgendaMedPac.get(i).getMedico().getNome(),
                    formato.format(listaAgendaMedPac.get(i).getAgenda().getDataAgenda()),
                    listaAgendaMedPac.get(i).getAgenda().getHoraAagenda(),
                    listaAgendaMedPac.get(i).getAgenda().getMotivoConsulta(),
                    listaAgendaMedPac.get(i).getAgenda().getStatus()
                });
            }
            CorDataLinha();
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
       int d = JOptionPane.showConfirmDialog(null, "Deseja apagar este registro?", "AVISO", JOptionPane.YES_NO_OPTION);
        if (d == 0) {
            try {
                if (jt_agenda.getSelectedRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Selecione um registro", "AVISO", JOptionPane.ERROR_MESSAGE);
                } else {
                    int[] rows = jt_agenda.getSelectedRows();
                    for (int i = 0; i < rows.length; i++) {
                        int codigo = (int) jt_agenda.getValueAt(rows[i], 0);
                        agendaCtrl.deletAgendaCtrl(codigo);
                    }
                    JOptionPane.showMessageDialog(null, "Resgistro apagado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
        limparTable();
        carregarAgenda();
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void limparTable() {
        DefaultTableModel modelo = (DefaultTableModel) jt_agenda.getModel();
        modelo.setNumRows(0);
    }

    private void carregarAgenda() {
        DefaultTableModel modelo = (DefaultTableModel) jt_agenda.getModel();
        listaAgendaMedPac = genericCtrl.getListaAgendaCtrl();
        int cont = listaAgendaMedPac.size();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaAgendaMedPac.get(i).getAgenda().getId_agenda(),
                listaAgendaMedPac.get(i).getPaciente().getNome(),
                listaAgendaMedPac.get(i).getMedico().getNome(),
                formato.format(listaAgendaMedPac.get(i).getAgenda().getDataAgenda()),
                listaAgendaMedPac.get(i).getAgenda().getHoraAagenda(),
                listaAgendaMedPac.get(i).getAgenda().getMotivoConsulta(),
                listaAgendaMedPac.get(i).getAgenda().getStatus()
            });
        }
        CorDataLinha();
    }

    private void CorDataLinha() {
        String status2 = new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis()));
        String status = "NÃO";
        jt_agenda.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable tabela, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(tabela, value, isSelected, hasFocus, row, column);
                Color c = Color.WHITE;
                Font f;
                Object texto = tabela.getValueAt(row, 3);
                Object texto2 = tabela.getValueAt(row, 6);
                if (status2.compareTo((String) texto) > 0) {
                    c = Color.RED;
                }
                if (texto2 != null && "SIM".equals(texto2.toString())) {
                    c = Color.CYAN;
                }
                label.setBackground(c);
                if (texto != null && status.equals(texto2.toString())) {
                    f = new Font("Arial", Font.BOLD, 12);
                    label.setFont(f);
                }
                jt_agenda.setSelectionForeground(Color.BLACK);

                return label;
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_realizada;
    private javax.swing.JTable jt_agenda;
    // End of variables declaration//GEN-END:variables
}
